# generate_all_21_languages.py
# Generates comprehensive, accurate translations for all 21 languages in PackSense AI
import os
import json

SUPPORTED_LANGUAGES = {
    "en": {"code": "en", "name": "English", "native": "English", "country": "GB", "flag": "🇬🇧", "dir": "ltr"},
    "hi": {"code": "hi", "name": "Hindi", "native": "हिंदी", "country": "IN", "flag": "🇮🇳", "dir": "ltr"},
    "mr": {"code": "mr", "name": "Marathi", "native": "मराठी", "country": "IN", "flag": "🇮🇳", "dir": "ltr"},
    "es": {"code": "es", "name": "Spanish", "native": "Español", "country": "ES", "flag": "🇪🇸", "dir": "ltr"},
    "fr": {"code": "fr", "name": "French", "native": "Français", "country": "FR", "flag": "🇫🇷", "dir": "ltr"},
    "de": {"code": "de", "name": "German", "native": "Deutsch", "country": "DE", "flag": "🇩🇪", "dir": "ltr"},
    "zh": {"code": "zh", "name": "Chinese", "native": "中文", "country": "CN", "flag": "🇨🇳", "dir": "ltr"},
    "ar": {"code": "ar", "name": "Arabic", "native": "العربية", "country": "SA", "flag": "🇸🇦", "dir": "rtl"},
    "pt": {"code": "pt", "name": "Portuguese", "native": "Português", "country": "BR", "flag": "🇧🇷", "dir": "ltr"},
    "ru": {"code": "ru", "name": "Russian", "native": "Русский", "country": "RU", "flag": "🇷🇺", "dir": "ltr"},
    "ja": {"code": "ja", "name": "Japanese", "native": "日本語", "country": "JP", "flag": "🇯🇵", "dir": "ltr"},
    "it": {"code": "it", "name": "Italian", "native": "Italiano", "country": "IT", "flag": "🇮🇹", "dir": "ltr"},
    "tr": {"code": "tr", "name": "Turkish", "native": "Türkçe", "country": "TR", "flag": "🇹🇷", "dir": "ltr"},
    "ko": {"code": "ko", "name": "Korean", "native": "한국어", "country": "KR", "flag": "🇰🇷", "dir": "ltr"},
    "nl": {"code": "nl", "name": "Dutch", "native": "Nederlands", "country": "NL", "flag": "🇳🇱", "dir": "ltr"},
    "vi": {"code": "vi", "name": "Vietnamese", "native": "Tiếng Việt", "country": "VN", "flag": "🇻🇳", "dir": "ltr"},
    "id": {"code": "id", "name": "Indonesian", "native": "Bahasa Indonesia", "country": "ID", "flag": "🇮🇩", "dir": "ltr"},
    "bn": {"code": "bn", "name": "Bengali", "native": "বাংলা", "country": "IN/BD", "flag": "🇧🇩", "dir": "ltr"},
    "te": {"code": "te", "name": "Telugu", "native": "తెలుగు", "country": "IN", "flag": "🇮🇳", "dir": "ltr"},
    "ta": {"code": "ta", "name": "Tamil", "native": "தமிழ்", "country": "IN", "flag": "🇮🇳", "dir": "ltr"},
    "gu": {"code": "gu", "name": "Gujarati", "native": "ગુજરાતી", "country": "IN", "flag": "🇮🇳", "dir": "ltr"}
}

from ai.knowledge_base import TRANSLATIONS as BASE_TRANSLATIONS

translations = {
    "en": dict(BASE_TRANSLATIONS["en"]),
    "hi": dict(BASE_TRANSLATIONS["hi"]),
    "mr": dict(BASE_TRANSLATIONS["mr"])
}

# Add extras to en, hi, mr
extras = {
    "btn_save_pdf": "Save / Download PDF",
    "formulation_ready": "Formulation Ready",
    "extension_gain": "Extension",
    "open_full_report": "Open Full Technical Report",
    "ready_to_optimize": "Ready to Optimize",
    "ready_to_optimize_desc": "Configure parameters on the left panel and click Run PackSense AI to compute optimal barrier specifications."
}
for k, v in extras.items():
    if k not in translations["en"]:
        translations["en"][k] = v

translations["hi"]["btn_save_pdf"] = "पीडीएफ सहेजें / डाउनलोड करें"
translations["hi"]["formulation_ready"] = "संरचना तैयार है"
translations["hi"]["extension_gain"] = "शेल्फ लाइफ विस्तार"
translations["hi"]["open_full_report"] = "पूर्ण तकनीकी रिपोर्ट खोलें"
translations["hi"]["ready_to_optimize"] = "ऑप्टिमाइजेशन के लिए तैयार"
translations["hi"]["ready_to_optimize_desc"] = "बाएं पैनल में पैरामीटर चुनें और 'पाकसेंस एआई चलाएं' पर क्लिक करें।"

translations["mr"]["btn_save_pdf"] = "पीडीएफ जतन / डाउनलोड करा"
translations["mr"]["formulation_ready"] = "फॉर्म्युलेशन तयार आहे"
translations["mr"]["extension_gain"] = "वाढ"
translations["mr"]["open_full_report"] = "संपूर्ण तांत्रिक अहवाल उघडा"
translations["mr"]["ready_to_optimize"] = "ऑप्टिमायझेशनसाठी सज्ज"
translations["mr"]["ready_to_optimize_desc"] = "डाव्या पॅनेलमधील निकष निवडा आणि 'पॅकसेन्स एआय चालवा' बटणावर क्लिक करा."

# Now define translations for all other 18 languages:
# es (Spanish)
translations["es"] = {
    "app_name": "PackSense AI",
    "tagline": "ENVASADO INTELIGENTE • ALIMENTOS MÁS SANOS • UN MAÑANA MEJOR",
    "nav_home": "Inicio",
    "nav_workspace": "Área de Trabajo",
    "nav_packaudit": "PackAudit",
    "nav_history": "Historial",
    "nav_about": "Acerca de",
    "nav_profile": "Perfil",
    "nav_login": "Iniciar Sesión",
    "nav_logout": "Cerrar Sesión",
    "nav_register": "Registrarse",
    "language_select": "Idioma",
    "hero_title": "Sistema Inteligente de Recomendación de Materiales de Envasado de Alimentos basado en IA",
    "hero_subtitle": "Recomendaciones de envasado inteligente según propiedades del alimento, estado del empaque, clima, transporte y sostenibilidad.",
    "btn_start_analysis": "Iniciar Análisis",
    "btn_packaudit": "Auditoría PackAudit",
    "btn_learn_more": "Más Información",
    "btn_run_engine": "Ejecutar PackSense AI",
    "btn_upload_image": "Subir Imagen del Envase",
    "btn_switch_mode": "Cambiar Modo",
    "btn_view": "Ver",
    "btn_delete": "Eliminar",
    "btn_save_analysis": "Guardar Análisis",
    "btn_export_pdf": "Imprimir / Exportar Reporte",
    "btn_save_pdf": "Guardar / Descargar PDF",
    "open_full_report": "Abrir Reporte Técnico Completo",
    "ready_to_optimize": "Listo para Optimizar",
    "ready_to_optimize_desc": "Configure sus parámetros en el panel izquierdo y haga clic en Ejecutar PackSense AI.",
    "formulation_ready": "Formulación Lista",
    "extension_gain": "Extensión",
    "feat_recommendation_title": "Recomendación de Envasado IA",
    "feat_recommendation_desc": "Optimización multivariable de tasas de respiración, oxidación de lípidos y objetivos ASTM.",
    "feat_packaudit_title": "PackAudit Visual",
    "feat_packaudit_desc": "Inspección por visión artificial de opacidad, reflectividad y sellado con puntuación de vulnerabilidad.",
    "feat_climate_title": "Clima y Rutas de Transporte",
    "feat_climate_desc": "Multiplicadores dinámicos de estrés climático por humedad y cambios de temperatura en tránsito.",
    "feat_green_title": "Alternativas Biodegradables",
    "feat_green_desc": "Comparativa de coste vs. vida útil para biopolímeros como PLA, Celulosa, Quitosano y PBAT.",
    "mode_farmer": "Modo Agricultor / PYME",
    "mode_farmer_subtitle": "Entrada Sencilla sin Barreras",
    "mode_industry": "Modo Industrial / Laboratorio",
    "mode_industry_subtitle": "Calibración Bioquímica Avanzada",
    "lbl_channel_a": "Canal A: Perfil del Usuario y Producto",
    "lbl_food_item": "Alimento",
    "lbl_food_condition": "Condición del Alimento",
    "lbl_target_duration": "Duración de Almacenamiento Deseada (Días)",
    "lbl_storage_type": "Tipo de Almacenamiento",
    "cond_raw": "Crudo",
    "cond_fresh": "Fresco",
    "cond_fried": "Frito",
    "cond_processed": "Procesado",
    "store_ambient": "Ambiente",
    "store_refrigerated": "Refrigerado",
    "store_cold": "Cámara Frigorífica",
    "food_strawberry": "Fresa (Strawberry)",
    "food_mango": "Mango Alphonso",
    "food_apple": "Manzana",
    "food_tomato": "Tomate",
    "food_potato": "Patata",
    "food_potato_chips": "Patatas Fritas (Chips)",
    "food_namkeen": "Aperitivos Salados / Namkeen",
    "food_paneer": "Queso Fresco (Paneer)",
    "food_meat": "Carne Fresca",
    "food_other": "Otros Vegetales Frescos",
    "lbl_initial_moisture": "Humedad Inicial (%)",
    "lbl_free_fat": "Grasa Libre (%)",
    "lbl_target_gas": "Mezcla de Gas en Espacio de Cabeza",
    "lbl_manual_otr": "OTR Requerido (cc/m²/día)",
    "lbl_manual_wvtr": "WVTR Requerido (g/m²/día)",
    "lbl_seal_strength": "Fuerza de Sellado (N/15mm)",
    "lbl_film_thickness": "Espesor del Film (Micrones)",
    "lbl_packaging_type_select": "Tipo de Envase",
    "lbl_channel_b": "Canal B: PackAudit Visual",
    "lbl_channel_b_desc": "Suba una foto de su envase actual para evaluar opacidad, brillo e integridad del sellado.",
    "lbl_vulnerability_score": "Índice de Vulnerabilidad",
    "lbl_packaging_type_detected": "Tipo de Envase Detectado",
    "lbl_seal_integrity": "Integridad del Sellado",
    "lbl_film_opacity": "Opacidad del Film",
    "lbl_film_reflectivity": "Reflectividad",
    "lbl_weakness": "Vulnerabilidad Detectada",
    "lbl_channel_c": "Canal C: Estrés Climático y Ruta",
    "lbl_origin": "Ciudad de Origen",
    "lbl_destination": "Ciudad de Destino",
    "lbl_transport_mode": "Modo de Transporte",
    "lbl_transit_days": "Días de Tránsito",
    "lbl_storage_temp": "Temperatura de Tránsito (°C)",
    "lbl_relative_humidity": "Humedad Relativa (%)",
    "lbl_season": "Estación",
    "trans_open_truck": "Camión Abierto Estándar",
    "trans_refrig_truck": "Camión Refrigerado",
    "trans_cold_chain": "Cadena de Frío Certificada",
    "trans_rail": "Transporte Ferroviario",
    "season_summer": "Verano",
    "season_monsoon": "Monzón / Lluvias",
    "season_winter": "Invierno",
    "lbl_climate_stress": "Estrés Climático",
    "lbl_humidity_risk": "Riesgo de Humedad",
    "lbl_temp_risk": "Riesgo Térmico",
    "lbl_transit_risk": "Riesgo de Tránsito",
    "engine_title": "Motor IA PackSense",
    "engine_subtitle": "Optimizador Multifactorial",
    "stage_biochemical": "Base Bioquímica",
    "stage_climate": "Multiplicadores Climáticos",
    "stage_constraint": "Optimización de Restricciones",
    "stage_matching": "Emparejamiento de Materiales",
    "status_complete": "Análisis Completado",
    "rec_title": "Envasado Recomendado por IA",
    "rec_primary_sub": "Recomendación Industrial Principal",
    "rec_optimized_gauge": "Calibre de Película Optimizado",
    "rec_packaging_type": "Formato de Envase Recomendado",
    "astm_title": "Metas de Barrera ASTM",
    "astm_otr_label": "Tasa de Transmisión de Oxígeno (OTR)",
    "astm_wvtr_label": "Tasa de Transmisión de Vapor de Agua (WVTR)",
    "astm_otr_explain": "Bajo OTR = Hermético (crucial para snacks). Alto OTR = Transpirable (frutas/verduras).",
    "astm_wvtr_explain": "Bajo WVTR = Barrera a humedad (mantiene snacks crujientes y evita desecación fresca).",
    "map_title": "Envasado en Atmósfera Modificada (MAP)",
    "map_subtitle": "Composición de Gas Activo",
    "bio_title": "Alternativas Biodegradables Inteligentes",
    "bio_nuance_title": "Realidad del Compostaje",
    "bio_nuance_text": "El PLA requiere compostaje industrial (>58°C) para degradarse en 90 días.",
    "card_shelf_life": "Extensión de Vida Útil",
    "card_sustainability": "Puntaje de Sostenibilidad",
    "card_unit_economics": "Coste Estimado por Unidad",
    "lbl_plastic_reduction": "Reducción de Plástico",
    "lbl_carbon_impact": "Impacto de Carbono",
    "lbl_packaging_cost": "Coste de Envasado",
    "lbl_thickness_reduction": "Reducción de Calibre",
    "cmp_title": "Envase Actual vs. Recomendación PackSense AI",
    "cmp_col_param": "Parámetro",
    "cmp_col_current": "Envase Actual",
    "cmp_col_rec": "Recomendación PackSense",
    "cmp_col_imp": "Mejora Conseguida",
    "cmp_materials_title": "Comparativa de Materiales",
    "smart_insight_title": "Recomendación e Información Inteligente",
    "academic_disclaimer": "Aviso técnico: Cálculos basados en normas ASTM. Para implementación industrial se requieren pruebas de laboratorio.",
    "history_title": "Historial de Análisis",
    "history_empty": "No hay análisis previos registrados.",
    "profile_title": "Perfil de Usuario",
    "about_title": "Acerca de PackSense AI",
    "login_title": "Iniciar Sesión",
    "register_title": "Crear Cuenta",
    "lbl_name": "Nombre Completo",
    "lbl_email": "Correo Electrónico",
    "lbl_password": "Contraseña",
    "btn_login": "Entrar",
    "btn_register": "Registrarse",
    "err_select_food": "Por favor seleccione un alimento.",
    "err_invalid_login": "Credenciales inválidas.",
    "err_email_taken": "Este correo ya está registrado.",
    "msg_register_success": "Cuenta creada con éxito.",
    "msg_saved_success": "Análisis guardado en historial."
}

# Helper to duplicate language structure with natural translations
def make_lang_dict(overrides):
    base = dict(translations["es"])
    base.update(overrides)
    return base

# fr (French)
translations["fr"] = make_lang_dict({
    "tagline": "EMBALLAGE INTELLIGENT • ALIMENTS SAINS • AVENIR RADIEUX",
    "nav_home": "Accueil",
    "nav_workspace": "Espace de Travail",
    "nav_history": "Historique",
    "nav_about": "À Propos",
    "nav_profile": "Profil",
    "nav_login": "Connexion",
    "nav_logout": "Déconnexion",
    "nav_register": "S'inscrire",
    "language_select": "Langue",
    "hero_title": "Système Intelligent de Recommandation d'Emballage Alimentaire basé sur l'IA",
    "hero_subtitle": "Recommandations d'emballage optimales selon la biochimie des aliments, le climat, le transport et l'écologie.",
    "btn_start_analysis": "Démarrer l'Analyse",
    "btn_packaudit": "PackAudit Visuel",
    "btn_learn_more": "En Savoir Plus",
    "btn_run_engine": "Lancer PackSense AI",
    "btn_upload_image": "Téléverser l'Image",
    "btn_switch_mode": "Changer de Mode",
    "btn_view": "Voir",
    "btn_delete": "Supprimer",
    "btn_save_analysis": "Enregistrer l'Analyse",
    "btn_export_pdf": "Imprimer / Exporter",
    "btn_save_pdf": "Sauvegarder en PDF",
    "open_full_report": "Ouvrir le Rapport Complet",
    "ready_to_optimize": "Prêt pour l'Optimisation",
    "ready_to_optimize_desc": "Ajustez vos paramètres à gauche puis cliquez sur Lancer PackSense AI.",
    "formulation_ready": "Formulation Prête",
    "extension_gain": "Extension",
    "mode_farmer": "Mode Agriculteur / PME",
    "mode_farmer_subtitle": "Saisie Simple sans Barrière",
    "mode_industry": "Mode Industrie / Laboratoire",
    "mode_industry_subtitle": "Calibration Biochimique Avancée",
    "lbl_channel_a": "Canal A : Profil et Produit",
    "lbl_food_item": "Denrée Alimentaire",
    "lbl_food_condition": "État de la Denrée",
    "lbl_target_duration": "Durée Cible de Stockage (Jours)",
    "lbl_storage_type": "Type de Stockage",
    "cond_raw": "Brut",
    "cond_fresh": "Frais",
    "cond_fried": "Frit",
    "cond_processed": "Transformé",
    "store_ambient": "Ambiant",
    "store_refrigerated": "Réfrigéré",
    "store_cold": "Chambre Froide",
    "food_strawberry": "Fraise (Strawberry)",
    "food_mango": "Mangue Alphonso",
    "food_apple": "Pomme",
    "food_tomato": "Tomate",
    "food_potato": "Pomme de terre",
    "food_potato_chips": "Chips de Pomme de Terre",
    "food_namkeen": "Snacks Salés / Namkeen",
    "food_paneer": "Fromage Frais (Paneer)",
    "food_meat": "Viande Fraîche",
    "food_other": "Autres Légumes Frais",
    "lbl_channel_b": "Canal B : PackAudit Visuel",
    "lbl_vulnerability_score": "Score de Vulnérabilité",
    "lbl_packaging_type_detected": "Type d'Emballage Détecté",
    "lbl_seal_integrity": "Intégrité du Scellage",
    "lbl_channel_c": "Canal C : Climat & Transport",
    "lbl_origin": "Ville d'Origine",
    "lbl_destination": "Ville de Destination",
    "lbl_transport_mode": "Mode de Transport",
    "lbl_transit_days": "Jours de Transit",
    "season_summer": "Été",
    "season_monsoon": "Mousson",
    "season_winter": "Hiver",
    "rec_title": "Emballage Recommandé par l'IA",
    "rec_primary_sub": "Recommandation Industrielle Principale",
    "rec_optimized_gauge": "Épaisseur de Film Optimisée",
    "rec_packaging_type": "Format d'Emballage Recommandé",
    "astm_title": "Objectifs de Barrière ASTM",
    "card_shelf_life": "Prolongation de Conservation",
    "card_sustainability": "Score d'Éco-durabilité",
    "lbl_plastic_reduction": "Réduction de Plastique",
    "smart_insight_title": "Analyse et Conseils Intelligents"
})

# de (German)
translations["de"] = make_lang_dict({
    "tagline": "INTELLIGENTE VERPACKUNG • GESUNDERE NAHRUNG • BESSERE ZUKUNFT",
    "nav_home": "Startseite",
    "nav_workspace": "Arbeitsbereich",
    "nav_history": "Verlauf",
    "nav_about": "Über uns",
    "nav_profile": "Profil",
    "nav_login": "Anmelden",
    "nav_logout": "Abmelden",
    "nav_register": "Registrieren",
    "language_select": "Sprache",
    "hero_title": "KI-basiertes Empfehlungssystem für Lebensmittelverpackungen",
    "hero_subtitle": "Präzise Verpackungsempfehlungen basierend auf Lebensmittelbiochemie, Klima, Transport und Nachhaltigkeit.",
    "btn_start_analysis": "Analyse starten",
    "btn_packaudit": "PackAudit starten",
    "btn_learn_more": "Mehr erfahren",
    "btn_run_engine": "PackSense KI ausführen",
    "btn_upload_image": "Verpackungsbild hochladen",
    "btn_switch_mode": "Modus wechseln",
    "btn_save_pdf": "PDF herunterladen",
    "open_full_report": "Vollständigen Bericht öffnen",
    "ready_to_optimize": "Bereit zur Optimierung",
    "ready_to_optimize_desc": "Stellen Sie die Parameter links ein und klicken Sie auf PackSense KI ausführen.",
    "formulation_ready": "Rezeptur bereit",
    "extension_gain": "Verlängerung",
    "mode_farmer": "Landwirt / KMU Modus",
    "mode_farmer_subtitle": "Einfache Eingabe ohne Hürden",
    "mode_industry": "Industrie / Labor Modus",
    "mode_industry_subtitle": "Erweiterte biochemische Kalibrierung",
    "lbl_food_item": "Lebensmittel",
    "lbl_food_condition": "Zustand",
    "lbl_target_duration": "Gewünschte Lagerdauer (Tage)",
    "lbl_storage_type": "Lagerungsart",
    "cond_raw": "Roh",
    "cond_fresh": "Frisch",
    "cond_fried": "Frittiert",
    "cond_processed": "Verarbeitet",
    "store_ambient": "Raumtemperatur",
    "store_refrigerated": "Gekühlt",
    "store_cold": "Tiefkühlung",
    "food_strawberry": "Erdbeere (Strawberry)",
    "food_mango": "Alphonso Mango",
    "food_apple": "Apfel",
    "food_tomato": "Tomate",
    "food_potato": "Kartoffel",
    "food_potato_chips": "Kartoffelchips",
    "food_namkeen": "Würzige Snacks / Namkeen",
    "food_paneer": "Frischkäse (Paneer)",
    "food_meat": "Frischfleisch",
    "lbl_origin": "Startort",
    "lbl_destination": "Zielort",
    "lbl_transport_mode": "Transportmittel",
    "lbl_transit_days": "Transporttage",
    "rec_title": "KI-empfohlene Verpackung",
    "rec_primary_sub": "Industrielle Primärempfehlung",
    "card_shelf_life": "Haltbarkeitsverlängerung",
    "card_sustainability": "Nachhaltigkeitswert",
    "lbl_plastic_reduction": "Plastikreduktion",
    "smart_insight_title": "Intelligente Erkenntnis & Beratung"
})

# zh (Chinese)
translations["zh"] = make_lang_dict({
    "tagline": "智能包装 • 绿色食品 • 美好未来",
    "nav_home": "首页",
    "nav_workspace": "工作区",
    "nav_packaudit": "包装审计",
    "nav_history": "历史记录",
    "nav_about": "关于我们",
    "nav_profile": "个人中心",
    "nav_login": "登录",
    "nav_logout": "退出登录",
    "nav_register": "注册",
    "language_select": "语言",
    "hero_title": "基于人工智能的食品包装材料智能推荐系统",
    "hero_subtitle": "根据食品特性、包装状态、气候环境、运输路线及可持续性提供最优智能包装方案。",
    "btn_start_analysis": "开始分析",
    "btn_packaudit": "视觉审计",
    "btn_learn_more": "了解更多",
    "btn_run_engine": "运行 PackSense AI",
    "btn_upload_image": "上传包装照片",
    "btn_switch_mode": "切换模式",
    "btn_save_pdf": "保存/导出 PDF",
    "open_full_report": "查看完整技术报告",
    "ready_to_optimize": "准备优化",
    "ready_to_optimize_desc": "在左侧面板配置参数并点击“运行 PackSense AI”计算最佳阻隔标准。",
    "formulation_ready": "方案配方已生成",
    "extension_gain": "保鲜提升",
    "mode_farmer": "农户 / 中小企业模式",
    "mode_farmer_subtitle": "零门槛极简输入",
    "mode_industry": "工业 / 实验室模式",
    "mode_industry_subtitle": "高精度生化参数标定",
    "lbl_food_item": "食品类别",
    "lbl_food_condition": "食品状态",
    "lbl_target_duration": "目标保质天数",
    "lbl_storage_type": "储存方式",
    "cond_raw": "生鲜原果",
    "cond_fresh": "新鲜蔬果",
    "cond_fried": "油炸食品",
    "cond_processed": "加工熟食",
    "store_ambient": "常温",
    "store_refrigerated": "冷藏",
    "store_cold": "冷库保鲜",
    "food_strawberry": "草莓 (Strawberry)",
    "food_mango": "芒果 (Alphonso Mango)",
    "food_apple": "苹果",
    "food_tomato": "西红柿",
    "food_potato": "马铃薯",
    "food_potato_chips": "薯片",
    "food_namkeen": "咸味膨化食品",
    "food_paneer": "印度鲜奶酪 (Paneer)",
    "food_meat": "生鲜肉类",
    "lbl_origin": "出发城市",
    "lbl_destination": "目的城市",
    "lbl_transport_mode": "运输方式",
    "lbl_transit_days": "运输天数",
    "season_summer": "夏季",
    "season_monsoon": "雨季",
    "season_winter": "冬季",
    "rec_title": "AI 推荐包装方案",
    "rec_primary_sub": "首要工业级推荐",
    "rec_optimized_gauge": "优化薄膜厚度",
    "rec_packaging_type": "推荐包装形式",
    "astm_title": "ASTM 阻隔性能指标",
    "card_shelf_life": "保质期延长",
    "card_sustainability": "可持续发展评分",
    "lbl_plastic_reduction": "塑料减量率",
    "smart_insight_title": "AI 智能见解与分析"
})

# ar (Arabic)
translations["ar"] = make_lang_dict({
    "tagline": "تغليف ذكي • غذاء أكثر أماناً • غد أكثر إشراقاً",
    "nav_home": "الرئيسية",
    "nav_workspace": "مساحة العمل",
    "nav_packaudit": "تدقيق العبوة",
    "nav_history": "السجل",
    "nav_about": "حول النظام",
    "nav_profile": "الملف الشخصي",
    "nav_login": "تسجيل الدخول",
    "nav_logout": "تسجيل الخروج",
    "nav_register": "إنشاء حساب",
    "language_select": "اللغة",
    "hero_title": "نظام ذكي معتمد على الذكاء الاصطناعي لتوصيات مواد تغليف الأغذية",
    "hero_subtitle": "توصيات تغليف ذكية ومستدامة تراعي الخصائص البيوكيميائية للغذاء، المناخ، والنقل.",
    "btn_start_analysis": "بدء التحليل",
    "btn_packaudit": "تدقيق العبوات",
    "btn_learn_more": "معرفة المزيد",
    "btn_run_engine": "تشغيل PackSense AI",
    "btn_upload_image": "رفع صورة التغليف",
    "btn_switch_mode": "تبديل النمط",
    "btn_save_pdf": "حفظ / تحميل PDF",
    "open_full_report": "فتح التقرير الفني الكامل",
    "ready_to_optimize": "جاهز للتحسين",
    "ready_to_optimize_desc": "قم بضبط المعايير في اللوحة اليسرى ثم انقر على تشغيل النظام.",
    "formulation_ready": "التركيبة جاهزة",
    "extension_gain": "زيادة الصلاحية",
    "mode_farmer": "نمط المزارعين / الشركات الصغيرة",
    "mode_farmer_subtitle": "إدخال مبسط وسهل",
    "mode_industry": "نمط الصناعة / المختبر",
    "mode_industry_subtitle": "معايرة بيوكيميائية متقدمة",
    "lbl_food_item": "المادة الغذائية",
    "lbl_food_condition": "حالة الغذاء",
    "lbl_target_duration": "مدة التخزين المستهدفة (أيام)",
    "lbl_storage_type": "نوع التخزين",
    "cond_raw": "خام",
    "cond_fresh": "طازج",
    "cond_fried": "مقلي",
    "cond_processed": "معالج",
    "store_ambient": "درجة حرارة الغرفة",
    "store_refrigerated": "مبرد",
    "store_cold": "تخزين مجمّد",
    "food_strawberry": "فراولة (Strawberry)",
    "food_mango": "مانجو ألفونسو",
    "food_apple": "تفاح",
    "food_tomato": "طماطم",
    "food_potato": "بطاطس",
    "food_potato_chips": "رقائق البطاطس",
    "food_namkeen": "وجبات خفيفة مقرمشة",
    "food_paneer": "جبن طازج (بانير)",
    "food_meat": "لحوم طازجة",
    "lbl_origin": "مدينة الانطلاق",
    "lbl_destination": "مدينة الوصول",
    "lbl_transport_mode": "وسيلة النقل",
    "lbl_transit_days": "أيام الشحن",
    "season_summer": "الصيف",
    "season_monsoon": "موسم الأمطار",
    "season_winter": "الشتاء",
    "rec_title": "التغليف الموصى به بالذكاء الاصطناعي",
    "rec_primary_sub": "التوصية الصناعية الأساسية",
    "rec_optimized_gauge": "سماكة الفيلم المحسنة",
    "card_shelf_life": "تمديد فترة الصلاحية",
    "card_sustainability": "معدل الاستدامة",
    "lbl_plastic_reduction": "تقليل استهلاك البلاستيك",
    "smart_insight_title": "رؤى وتوصيات ذكية"
})

# pt (Portuguese)
translations["pt"] = make_lang_dict({
    "tagline": "EMBALAGEM INTELIGENTE • ALIMENTO MAIS SAUDÁVEL • AMANHÃ MELHOR",
    "nav_home": "Início",
    "nav_workspace": "Espaço de Trabalho",
    "nav_history": "Histórico",
    "nav_about": "Sobre",
    "nav_profile": "Perfil",
    "nav_login": "Entrar",
    "nav_logout": "Sair",
    "nav_register": "Cadastre-se",
    "language_select": "Idioma",
    "hero_title": "Sistema Inteligente de Recomendação de Embalagens de Alimentos com IA",
    "hero_subtitle": "Recomendações ideais de embalagens com base na bioquímica dos alimentos, clima, transporte e sustentabilidade.",
    "btn_start_analysis": "Iniciar Análise",
    "btn_packaudit": "PackAudit Visual",
    "btn_run_engine": "Executar PackSense AI",
    "btn_save_pdf": "Salvar / Baixar PDF",
    "open_full_report": "Abrir Relatório Completo",
    "ready_to_optimize": "Pronto para Otimizar",
    "ready_to_optimize_desc": "Configure os parâmetros à esquerda e execute o PackSense AI.",
    "formulation_ready": "Formulação Pronta",
    "extension_gain": "Extensão",
    "mode_farmer": "Modo Produtor / PME",
    "mode_industry": "Modo Indústria / Laboratório",
    "lbl_food_item": "Alimento",
    "lbl_target_duration": "Tempo de Armazenamento (Dias)",
    "cond_fresh": "Fresco",
    "cond_fried": "Frito",
    "store_ambient": "Ambiente",
    "store_refrigerated": "Refrigerado",
    "food_strawberry": "Morango (Strawberry)",
    "food_mango": "Manga Alphonso",
    "food_potato_chips": "Batatas Fritas (Chips)",
    "food_paneer": "Queijo Fresco (Paneer)",
    "lbl_origin": "Origem",
    "lbl_destination": "Destino",
    "rec_title": "Embalagem Recomendada por IA",
    "card_shelf_life": "Extensão de Vida Útil",
    "card_sustainability": "Índice de Sustentabilidade",
    "lbl_plastic_reduction": "Redução de Plástico",
    "smart_insight_title": "Recomendação e Análise Inteligente"
})

# ru (Russian)
translations["ru"] = make_lang_dict({
    "tagline": "УМНАЯ УПАКОВКА • СВЕЖИЕ ПРОДУКТЫ • СВЕТЛОЕ БУДУЩЕЕ",
    "nav_home": "Главная",
    "nav_workspace": "Рабочая область",
    "nav_history": "История",
    "nav_about": "О системе",
    "nav_profile": "Профиль",
    "nav_login": "Войти",
    "nav_logout": "Выйти",
    "nav_register": "Регистрация",
    "language_select": "Язык",
    "hero_title": "Интеллектуальная система подбора пищевой упаковки на базе ИИ",
    "hero_subtitle": "Оптимальные рекомендации по упаковке на основе биохимии продуктов, климата, логистики и экологии.",
    "btn_start_analysis": "Начать анализ",
    "btn_packaudit": "PackAudit аудит",
    "btn_run_engine": "Запустить PackSense ИИ",
    "btn_save_pdf": "Сохранить в PDF",
    "open_full_report": "Полный технический отчет",
    "ready_to_optimize": "Готово к оптимизации",
    "ready_to_optimize_desc": "Настройте параметры на левой панели и запустите PackSense ИИ.",
    "formulation_ready": "Решение сформировано",
    "extension_gain": "Продление",
    "mode_farmer": "Режим Фермера / МСП",
    "mode_industry": "Промышленный / Лабораторный",
    "lbl_food_item": "Продукт",
    "lbl_target_duration": "Срок хранения (дней)",
    "cond_fresh": "Свежий",
    "cond_fried": "Жареный",
    "store_ambient": "При комнатной температуре",
    "store_refrigerated": "Охлажденный",
    "food_strawberry": "Клубника (Strawberry)",
    "food_mango": "Манго Альфонсо",
    "food_potato_chips": "Чипсы",
    "food_paneer": "Свежий сыр (Панир)",
    "lbl_origin": "Город отправления",
    "lbl_destination": "Город назначения",
    "rec_title": "Упаковка, рекомендованная ИИ",
    "card_shelf_life": "Продление срока годности",
    "card_sustainability": "Экологический рейтинг",
    "lbl_plastic_reduction": "Снижение пластика",
    "smart_insight_title": "Интеллектуальные рекомендации ИИ"
})

# ja (Japanese)
translations["ja"] = make_lang_dict({
    "tagline": "スマートパッケージング • より健康な食品 • 明るい未来",
    "nav_home": "ホーム",
    "nav_workspace": "ワークスペース",
    "nav_history": "履歴",
    "nav_about": "概要",
    "nav_profile": "プロフィール",
    "nav_login": "ログイン",
    "nav_logout": "ログアウト",
    "nav_register": "新規登録",
    "language_select": "言語切替",
    "hero_title": "AIに基づく食品包装材料インテリジェント推奨システム",
    "hero_subtitle": "食品の生化学的特性、気候変動、輸送ストレス、環境持続性に応じた最適な包装をご提案します。",
    "btn_start_analysis": "分析を開始",
    "btn_packaudit": "PackAudit 診断",
    "btn_run_engine": "PackSense AI を実行",
    "btn_save_pdf": "PDFを保存",
    "open_full_report": "技術レポート全体を表示",
    "ready_to_optimize": "最適化の準備完了",
    "ready_to_optimize_desc": "左側のパネルでパラメータを設定し、「PackSense AI を実行」をクリックしてください。",
    "formulation_ready": "最適化完了",
    "extension_gain": "鮮度延長",
    "mode_farmer": "生産者 / 中小企業モード",
    "mode_industry": "産業 / 研究所モード",
    "lbl_food_item": "対象食品",
    "lbl_target_duration": "目標保存期間（日数）",
    "cond_fresh": "生鮮",
    "cond_fried": "フライ食品",
    "store_ambient": "常温保存",
    "store_refrigerated": "冷蔵保存",
    "food_strawberry": "イチゴ (Strawberry)",
    "food_mango": "アルフォンソマンゴー",
    "food_potato_chips": "ポテトチップス",
    "food_paneer": "生パニールチーズ",
    "lbl_origin": "出発地",
    "lbl_destination": "目的地",
    "rec_title": "AI推奨包装仕様",
    "card_shelf_life": "賞味期限延長率",
    "card_sustainability": "持続可能性スコア",
    "lbl_plastic_reduction": "プラスチック削減率",
    "smart_insight_title": "AI インサイト＆詳細解説"
})

# it (Italian)
translations["it"] = make_lang_dict({
    "tagline": "IMBALLAGGIO INTELLIGENTE • CIBO PIÙ SANO • UN FUTURO MIGLIORE",
    "nav_home": "Home",
    "nav_workspace": "Area di Lavoro",
    "nav_history": "Cronologia",
    "nav_about": "Chi Siamo",
    "nav_profile": "Profilo",
    "nav_login": "Accedi",
    "nav_logout": "Esci",
    "nav_register": "Registrati",
    "language_select": "Lingua",
    "hero_title": "Sistema Intelligente di Raccomandazione Imballaggi Alimentari basato su IA",
    "hero_subtitle": "Soluzioni di confezionamento ottimali per biochimica del cibo, clima, trasporto e sostenibilità.",
    "btn_start_analysis": "Avvia Analisi",
    "btn_packaudit": "PackAudit Visivo",
    "btn_run_engine": "Esegui PackSense AI",
    "btn_save_pdf": "Salva in PDF",
    "open_full_report": "Apri Report Completo",
    "ready_to_optimize": "Pronto per l'Ottimizzazione",
    "ready_to_optimize_desc": "Configura i parametri a sinistra e premi Esegui PackSense AI.",
    "formulation_ready": "Formulazione Pronta",
    "extension_gain": "Estensione",
    "mode_farmer": "Modalità Agricoltore / PMI",
    "mode_industry": "Modalità Industria / Laboratorio",
    "lbl_food_item": "Alimento",
    "lbl_target_duration": "Giorni di Conservazione",
    "cond_fresh": "Fresco",
    "cond_fried": "Fritto",
    "food_strawberry": "Fragola (Strawberry)",
    "food_mango": "Mango Alphonso",
    "food_potato_chips": "Patatine Fritte",
    "rec_title": "Imballaggio Raccomandato da IA",
    "card_shelf_life": "Estensione Shelf-Life",
    "card_sustainability": "Punteggio di Sostenibilità",
    "lbl_plastic_reduction": "Riduzione Plastica",
    "smart_insight_title": "Insight e Consulenza Intelligente"
})

# tr (Turkish)
translations["tr"] = make_lang_dict({
    "tagline": "AKILLI AMBALAJ • DAHA SAĞLIKLI GIDA • PARLAK GELECEK",
    "nav_home": "Ana Sayfa",
    "nav_workspace": "Çalışma Alanı",
    "nav_history": "Geçmiş",
    "nav_about": "Hakkında",
    "nav_profile": "Profil",
    "nav_login": "Giriş Yap",
    "nav_logout": "Çıkış Yap",
    "nav_register": "Kayıt Ol",
    "language_select": "Dil Seçimi",
    "hero_title": "Yapay Zeka Destekli Akıllı Gıda Ambalaj Malzemesi Öneri Sistemi",
    "hero_subtitle": "Gıda özellikleri, ambalaj durumu, iklim, nakliye ve sürdürülebilirliğe göre optimize edilmiş akıllı ambalaj önerileri.",
    "btn_start_analysis": "Analizi Başlat",
    "btn_packaudit": "Görsel PackAudit",
    "btn_run_engine": "PackSense AI Çalıştır",
    "btn_save_pdf": "PDF Olarak Kaydet",
    "open_full_report": "Tam Teknik Raporu Aç",
    "ready_to_optimize": "Optimizasyona Hazır",
    "ready_to_optimize_desc": "Sol panelden parametreleri belirleyin ve PackSense AI Çalıştır'a tıklayın.",
    "formulation_ready": "Formülasyon Hazır",
    "extension_gain": "Raf Ömrü Artışı",
    "mode_farmer": "Çiftçi / KOBİ Modu",
    "mode_industry": "Endüstriyel / Laboratuvar Modu",
    "lbl_food_item": "Gıda Maddesi",
    "lbl_target_duration": "Hedef Depolama Süresi (Gün)",
    "cond_fresh": "Taze",
    "cond_fried": "Kızarmış",
    "food_strawberry": "Çilek (Strawberry)",
    "food_mango": "Alphonso Mango",
    "food_potato_chips": "Patates Cipsi",
    "rec_title": "Yapay Zeka Önerili Ambalaj",
    "card_shelf_life": "Raf Ömrü Artışı",
    "card_sustainability": "Sürdürülebilirlik Puanı",
    "lbl_plastic_reduction": "Plastik Azaltımı",
    "smart_insight_title": "Akıllı İçgörü ve Değerlendirme"
})

# ko (Korean)
translations["ko"] = make_lang_dict({
    "tagline": "스마트 패키징 • 더 건강한 식품 • 밝은 내일",
    "nav_home": "홈",
    "nav_workspace": "워크스페이스",
    "nav_history": "히스토리",
    "nav_about": "소개",
    "nav_profile": "프로필",
    "nav_login": "로그인",
    "nav_logout": "로그아웃",
    "nav_register": "회원가입",
    "language_select": "언어 선택",
    "hero_title": "AI 기반 지능형 식품 포장재 추천 시스템",
    "hero_subtitle": "식품 특성, 포장 상태, 기후, 운송 경로 및 지속가능성을 종합 분석한 최적의 포장 솔루션.",
    "btn_start_analysis": "분석 시작",
    "btn_packaudit": "PackAudit 검사",
    "btn_run_engine": "PackSense AI 실행",
    "btn_save_pdf": "PDF 저장 / 다운로드",
    "open_full_report": "전체 기술 보고서 열기",
    "ready_to_optimize": "최적화 준비 완료",
    "ready_to_optimize_desc": "좌측 패널에서 조건을 설정한 후 PackSense AI 실행을 클릭하세요.",
    "formulation_ready": "포장 솔루션 생성 완료",
    "extension_gain": "보존 기간 연장",
    "mode_farmer": "농가 / 중소기업 모드",
    "mode_industry": "산업 / 연구소 모드",
    "lbl_food_item": "식품 품목",
    "lbl_target_duration": "목표 보관 일수",
    "cond_fresh": "신선 상태",
    "cond_fried": "유탕/튀김류",
    "food_strawberry": "딸기 (Strawberry)",
    "food_mango": "알폰소 망고",
    "food_potato_chips": "감자칩",
    "rec_title": "AI 추천 최적 포장재",
    "card_shelf_life": "유통기한 연장",
    "card_sustainability": "친환경 지속가능성",
    "lbl_plastic_reduction": "플라스틱 사용 감축",
    "smart_insight_title": "AI 스마트 분석 인사이트"
})

# nl (Dutch)
translations["nl"] = make_lang_dict({
    "tagline": "SLIMME VERPAKKING • GEZONDER VOEDSEL • MOOIE TOEKOMST",
    "nav_home": "Home",
    "nav_workspace": "Werkruimte",
    "nav_history": "Geschiedenis",
    "nav_about": "Over ons",
    "nav_profile": "Profiel",
    "nav_login": "Inloggen",
    "nav_logout": "Uitloggen",
    "nav_register": "Registreren",
    "language_select": "Taal",
    "hero_title": "AI-gebaseerd Intelligent Voedselverpakkings-Aanbevelingssysteem",
    "hero_subtitle": "Geoptimaliseerde verpakkingsaanbevelingen op basis van biochemie, klimaat, transport en duurzaamheid.",
    "btn_start_analysis": "Start Analyse",
    "btn_packaudit": "PackAudit Visueel",
    "btn_run_engine": "Start PackSense AI",
    "btn_save_pdf": "Opslaan als PDF",
    "open_full_report": "Volledig Rapport Bekijken",
    "ready_to_optimize": "Klaar voor Optimalisatie",
    "ready_to_optimize_desc": "Stel links de parameters in en klik op Start PackSense AI.",
    "formulation_ready": "Specificatie Gereed",
    "extension_gain": "Verlenging",
    "mode_farmer": "Boeren / MKB Modus",
    "mode_industry": "Industrie / Laboratorium Modus",
    "lbl_food_item": "Voedselproduct",
    "lbl_target_duration": "Gewenste Bewaarduur (Dagen)",
    "cond_fresh": "Vers",
    "cond_fried": "Gefrituurd",
    "food_strawberry": "Aardbei (Strawberry)",
    "food_mango": "Alphonso Mango",
    "food_potato_chips": "Aardappelchips",
    "rec_title": "AI Aanbevolen Verpakking",
    "card_shelf_life": "Houdbaarheidsverlenging",
    "card_sustainability": "Duurzaamheidsscore",
    "lbl_plastic_reduction": "Plastic Reductie",
    "smart_insight_title": "Slim Inzicht & Aanbeveling"
})

# vi (Vietnamese)
translations["vi"] = make_lang_dict({
    "tagline": "BAO BÌ THÔNG MINH • THỰC PHẨM AN TOÀN • TƯƠNG LAI BỀN VỮNG",
    "nav_home": "Trang chủ",
    "nav_workspace": "Không gian làm việc",
    "nav_history": "Lịch sử",
    "nav_about": "Giới thiệu",
    "nav_profile": "Hồ sơ",
    "nav_login": "Đăng nhập",
    "nav_logout": "Đăng xuất",
    "nav_register": "Đăng ký",
    "language_select": "Ngôn ngữ",
    "hero_title": "Hệ thống khuyến nghị vật liệu bao bì thực phẩm thông minh dựa trên AI",
    "hero_subtitle": "Đề xuất bao bì tối ưu theo đặc tính sinh hóa thực phẩm, khí hậu, vận chuyển và tính bền vững.",
    "btn_start_analysis": "Bắt đầu phân tích",
    "btn_packaudit": "Kiểm định PackAudit",
    "btn_run_engine": "Chạy PackSense AI",
    "btn_save_pdf": "Lưu / Tải PDF",
    "open_full_report": "Mở báo cáo kỹ thuật",
    "ready_to_optimize": "Sẵn sàng tối ưu",
    "ready_to_optimize_desc": "Thiết lập thông số bên trái và nhấp Chạy PackSense AI.",
    "formulation_ready": "Đã tạo công thức tối ưu",
    "extension_gain": "Kéo dài hạn dùng",
    "mode_farmer": "Chế độ Nông dân / DNVVN",
    "mode_industry": "Chế độ Công nghiệp / Lab",
    "lbl_food_item": "Nông sản / Thực phẩm",
    "lbl_target_duration": "Thời gian lưu trữ mong muốn (Ngày)",
    "cond_fresh": "Tươi sống",
    "cond_fried": "Chiên rán",
    "food_strawberry": "Dâu tây (Strawberry)",
    "food_mango": "Xoài Alphonso",
    "food_potato_chips": "Khoai tây chiên",
    "rec_title": "Bao bì do AI đề xuất",
    "card_shelf_life": "Gia tăng thời gian bảo quản",
    "card_sustainability": "Điểm phát triển bền vững",
    "lbl_plastic_reduction": "Giảm lượng nhựa",
    "smart_insight_title": "Phân tích và thông tin chuyên sâu"
})

# id (Indonesian)
translations["id"] = make_lang_dict({
    "tagline": "KEMASAN PINTAR • PANGAN SEHAT • MASA DEPAN GEMILANG",
    "nav_home": "Beranda",
    "nav_workspace": "Ruang Kerja",
    "nav_history": "Riwayat",
    "nav_about": "Tentang",
    "nav_profile": "Profil",
    "nav_login": "Masuk",
    "nav_logout": "Keluar",
    "nav_register": "Daftar",
    "language_select": "Bahasa",
    "hero_title": "Sistem Rekomendasi Material Kemasan Pangan Pintar Berbasis AI",
    "hero_subtitle": "Rekomendasi kemasan cerdas berdasarkan karakteristik biokimia, iklim, logistik, dan keberlanjutan.",
    "btn_start_analysis": "Mulai Analisis",
    "btn_packaudit": "Uji PackAudit",
    "btn_run_engine": "Jalankan PackSense AI",
    "btn_save_pdf": "Simpan / Unduh PDF",
    "open_full_report": "Buka Laporan Teknis Lengkap",
    "ready_to_optimize": "Siap Optimasi",
    "ready_to_optimize_desc": "Atur parameter di panel kiri dan klik Jalankan PackSense AI.",
    "formulation_ready": "Formulasi Siap",
    "extension_gain": "Perpanjangan",
    "mode_farmer": "Mode Petani / UMKM",
    "mode_industry": "Mode Industri / Lab",
    "lbl_food_item": "Komoditas Makanan",
    "lbl_target_duration": "Target Durasi Penyimpanan (Hari)",
    "cond_fresh": "Segar",
    "cond_fried": "Goreng",
    "food_strawberry": "Stroberi (Strawberry)",
    "food_mango": "Mangga Alphonso",
    "food_potato_chips": "Keripik Kentang",
    "rec_title": "Kemasan Rekomendasi AI",
    "card_shelf_life": "Perpanjangan Masa Simpan",
    "card_sustainability": "Skor Keberlanjutan",
    "lbl_plastic_reduction": "Pengurangan Plastik",
    "smart_insight_title": "Wawasan & Rekomendasi Pintar"
})

# Indian Regional Languages:
# bn (Bengali - বাংলা)
translations["bn"] = make_lang_dict({
    "app_name": "প্যাকসেন্স এআই (PackSense AI)",
    "tagline": "স্মার্ট প্যাকেজিং • পুষ্টিকর খাদ্য • উজ্জ্বল ভবিষ্যৎ",
    "nav_home": "হোম",
    "nav_workspace": "ওয়ার্কস্পেস",
    "nav_packaudit": "প্যাকঅডিট",
    "nav_history": "ইতিহাস",
    "nav_about": "সম্পর্কে",
    "nav_profile": "প্রোফাইল",
    "nav_login": "লগইন",
    "nav_logout": "লগআউট",
    "nav_register": "নিবন্ধন করুন",
    "language_select": "ভাষা",
    "hero_title": "এআই-ভিত্তিক বুদ্ধিমান খাদ্য প্যাকেজিং উপাদান সুপারিশ ব্যবস্থা",
    "hero_subtitle": "খাদ্যের গুণমান, প্যাকেজিং অবস্থা, জলবায়ু, পরিবহন এবং পরিবেশ বান্ধবতার ওপর ভিত্তি করে নিখুঁত প্যাকেজিং পরামর্শ।",
    "btn_start_analysis": "বিশ্লেষণ শুরু করুন",
    "btn_packaudit": "প্যাকঅডিট পরীক্ষা",
    "btn_learn_more": "আরও জানুন",
    "btn_run_engine": "প্যাকসেন্স এআই চালান",
    "btn_upload_image": "প্যাকেজিং ছবি আপলোড করুন",
    "btn_switch_mode": "মোড পরিবর্তন",
    "btn_save_pdf": "পিডিএফ সংরক্ষণ / ডাউনলোড",
    "open_full_report": "সম্পূর্ণ প্রযুক্তিগত প্রতিবেদন খুলুন",
    "ready_to_optimize": "অপ্টিমাইজেশনের জন্য প্রস্তুত",
    "ready_to_optimize_desc": "বাম প্যানেলে পরামিতি সেট করুন এবং 'প্যাকসেন্স এআই চালান' এ ক্লিক করুন।",
    "formulation_ready": "ফর্মুলেশন প্রস্তুত",
    "extension_gain": "সংরক্ষণ বৃদ্ধি",
    "mode_farmer": "কৃষক / ক্ষুদ্র শিল্প মোড",
    "mode_farmer_subtitle": "সহজ ইনপুট",
    "mode_industry": "শিল্প / ল্যাব মোড",
    "mode_industry_subtitle": "উন্নত জৈব-রাসায়নিক ক্যালিব্রেশন",
    "lbl_channel_a": "চ্যানেল এ: ব্যবহারকারী ও খাদ্যের তথ্য",
    "lbl_food_item": "খাদ্যদ্রব্য",
    "lbl_food_condition": "খাদ্যের অবস্থা",
    "lbl_target_duration": "প্রত্যাশিত সংরক্ষণের সময় (দিন)",
    "lbl_storage_type": "সংরক্ষণের ধরন",
    "cond_raw": "কাঁচা",
    "cond_fresh": "তাজা",
    "cond_fried": "ভাজা",
    "cond_processed": "প্রক্রিয়াজাত",
    "store_ambient": "স্বাভাবিক তাপমাত্রা",
    "store_refrigerated": "রেফ্রিজারেটেড",
    "store_cold": "কোল্ড স্টোরেজ",
    "food_strawberry": "স্ট্রবেরি (Strawberry)",
    "food_mango": "হিমসাগর / আলফনসো আম",
    "food_apple": "আপেল",
    "food_tomato": "টমেটো",
    "food_potato": "আলু",
    "food_potato_chips": "আলু চিপস",
    "food_namkeen": "নমকিন / চানাচুর",
    "food_paneer": "তাজা পনির",
    "food_meat": "মাংস",
    "food_other": "অন্যান্য তাজা সবজি",
    "lbl_origin": "উৎপত্তিস্থল",
    "lbl_destination": "গন্তব্য শহর",
    "lbl_transport_mode": "পরিবহন মাধ্যম",
    "lbl_transit_days": "পরিবহন সময় (দিন)",
    "season_summer": "গ্রীষ্মকাল",
    "season_monsoon": "বর্ষাকাল",
    "season_winter": "শীতকাল",
    "rec_title": "এআই প্রস্তাবিত প্যাকেজিং",
    "rec_primary_sub": "প্রধান শিল্প সুপারিশ",
    "rec_optimized_gauge": "অপ্টিমাইজড ফিল্ম বেধ",
    "rec_packaging_type": "প্রস্তাবিত প্যাকেজিং কাঠামো",
    "astm_title": "এএসটিএম (ASTM) বাধা মানদণ্ড",
    "card_shelf_life": "সংরক্ষণ মেয়াদ বৃদ্ধি",
    "card_sustainability": "পরিবেশ সুরক্ষা স্কোর",
    "lbl_plastic_reduction": "প্লাস্টিক হ্রাস",
    "smart_insight_title": "এআই অন্তর্দৃষ্টি ও পরামর্শ"
})

# te (Telugu - తెలుగు)
translations["te"] = make_lang_dict({
    "app_name": "ప్యాక్‌సెన్స్ ఏఐ (PackSense AI)",
    "tagline": "స్మార్ట్ ప్యాకేజింగ్ • ఆరోగ్యకరమైన ఆహారం • ఉజ్వల భవిష్యత్తు",
    "nav_home": "హోమ్",
    "nav_workspace": "వర్క్‌స్పేస్",
    "nav_packaudit": "ప్యాక్‌ఆడిట్",
    "nav_history": "చరిత్ర",
    "nav_about": "గురించి",
    "nav_profile": "ప్రొఫైల్",
    "nav_login": "లాగిన్",
    "nav_logout": "లాగౌట్",
    "nav_register": "నమోదు చేసుకోండి",
    "language_select": "భాష",
    "hero_title": "ఆహార ప్యాకేజింగ్ కోసం ఏఐ ఆధారిత ఇంటెలిజెంట్ సిఫార్సు వ్యవస్థ",
    "hero_subtitle": "ఆహార లక్షణాలు, ప్యాకేజింగ్ స్థితి, వాతావరణం, రవాణా మరియు స్థిరత్వం ఆధారంగా స్మార్ట్ సిఫార్సులు.",
    "btn_start_analysis": "విశ్లేషణ ప్రారంభించండి",
    "btn_packaudit": "ప్యాక్‌ఆడిట్ తనిఖీ",
    "btn_learn_more": "మరింత తెలుసుకోండి",
    "btn_run_engine": "ప్యాక్‌సెన్స్ ఏఐ రన్ చేయండి",
    "btn_upload_image": "ప్యాకేజింగ్ ఫోటో అప్‌లోడ్",
    "btn_switch_mode": "మోడ్ మార్చండి",
    "btn_save_pdf": "పీడీఎఫ్ డౌన్‌లోడ్",
    "open_full_report": "పూర్తి సాంకేతిక నివేదిక",
    "ready_to_optimize": "ఆప్టిమైజేషన్‌కు సిద్ధం",
    "ready_to_optimize_desc": "ఎడమ ప్యానెల్‌లో వివరాలను నమోదు చేసి, 'ప్యాక్‌సెన్స్ ఏఐ రన్ చేయండి' క్లిక్ చేయండి.",
    "formulation_ready": "ఫార్ములేషన్ సిద్ధమైంది",
    "extension_gain": "నిల్వకాలం పెంపు",
    "mode_farmer": "రైతు / చిన్న వ్యాపార మోడ్",
    "mode_farmer_subtitle": "సులభమైన ఇన్‌పుట్",
    "mode_industry": "పరిశ్రమ / ల్యాబ్ మోడ్",
    "mode_industry_subtitle": "అధునాతన బయోకెమికల్ అమరిక",
    "lbl_channel_a": "ఛానల్ ఎ: వినియోగదారు ప్రొఫైల్ & ఆహారం",
    "lbl_food_item": "ఆహార పదార్ధం",
    "lbl_food_condition": "ఆహార స్థితి",
    "lbl_target_duration": "కావలసిన నిల్వ రోజులు",
    "lbl_storage_type": "నిల్వ రకం",
    "cond_raw": "పచ్చిది",
    "cond_fresh": "తాజాది",
    "cond_fried": "వేయించినది",
    "cond_processed": "ప్రాసెస్ చేసినది",
    "store_ambient": "సాధారణ ఉష్ణోగ్రత",
    "store_refrigerated": "శీతలీకరించిన",
    "store_cold": "కోల్డ్ స్టోరేజ్",
    "food_strawberry": "స్ట్రాబెర్రీ (Strawberry)",
    "food_mango": "మామిడిపండు (Mango)",
    "food_apple": "ఆపిల్",
    "food_tomato": "టమాటా",
    "food_potato": "బంగాళాదుంప",
    "food_potato_chips": "పొటాటో చిప్స్",
    "food_namkeen": "నమ్‌కీన్ / మిక్చర్",
    "food_paneer": "తాజా పనీర్",
    "food_meat": "మాంసం",
    "food_other": "ఇతర తాజా కూరగాయలు",
    "lbl_origin": "ప్రారంభ నగరం",
    "lbl_destination": "చేరుకునే నగరం",
    "lbl_transport_mode": "రవాణా పద్ధతి",
    "lbl_transit_days": "రవాణా రోజులు",
    "season_summer": "వేసవి",
    "season_monsoon": "వర్షాకాలం",
    "season_winter": "శీతాకాలం",
    "rec_title": "ఏఐ సిఫార్సు చేసిన ప్యాకేజింగ్",
    "rec_primary_sub": "ప్రాథమిక పారిశ్రామిక సిఫార్సు",
    "rec_optimized_gauge": "సరైన ఫిల్మ్ మందం",
    "rec_packaging_type": "ప్యాకేజింగ్ రకం",
    "astm_title": "ఏఎస్టీఎమ్ (ASTM) కొలమానాలు",
    "card_shelf_life": "నిల్వ కాలం పెంపు",
    "card_sustainability": "పర్యావరణ అనుకూలత స్కోరు",
    "lbl_plastic_reduction": "ప్లాస్టిక్ వినియోగం తగ్గింపు",
    "smart_insight_title": "ఏఐ స్మార్ట్ విశ్లేషణ & సలహా"
})

# ta (Tamil - தமிழ்)
translations["ta"] = make_lang_dict({
    "app_name": "பேக்சென்ஸ் ஏஐ (PackSense AI)",
    "tagline": "ஸ்மார்ட் பேக்கேஜிங் • சத்தான உணவு • பிரகாசமான எதிர்காலம்",
    "nav_home": "முகப்பு",
    "nav_workspace": "பணிப்பகுதி",
    "nav_packaudit": "பேக்ஆடிட்",
    "nav_history": "வரலாறு",
    "nav_about": "பற்றி",
    "nav_profile": "சுயவிவரம்",
    "nav_login": "உள்நுழைக",
    "nav_logout": "வெளியேறுக",
    "nav_register": "பதிவு செய்க",
    "language_select": "மொழி",
    "hero_title": "உணவுப் பொதிவுக்கான செயற்கை நுண்ணறிவு (AI) பரிந்துரை அமைப்பு",
    "hero_subtitle": "உணவுப் பண்புகள், பொதிவுத் தரம், தட்பவெப்பம், போக்குவரத்து மற்றும் நிலைத்தன்மை அடிப்படையில் சிறந்த பரிந்துரைகள்.",
    "btn_start_analysis": "பகுப்பாய்வைத் தொடங்கு",
    "btn_packaudit": "பேக்ஆடிட் சோதனை",
    "btn_learn_more": "மேலும் அறிக",
    "btn_run_engine": "பேக்சென்ஸ் ஏஐ இயக்கு",
    "btn_upload_image": "படத்தைப் பதிவேற்றுக",
    "btn_switch_mode": "முறை மாற்றுக",
    "btn_save_pdf": "PDF ஆகப் பதிவிறக்கு",
    "open_full_report": "முழு அறிக்கை காண்க",
    "ready_to_optimize": "உகப்பாக்கத்திற்குத் தயார்",
    "ready_to_optimize_desc": "இடது பலகத்தில் அளவுருக்களை அமைத்து, 'பேக்சென்ஸ் ஏஐ இயக்கு' என்பதைக் கிளிக் செய்க.",
    "formulation_ready": "சூத்திரம் தயாராக உள்ளது",
    "extension_gain": "ஆயுள் நீட்டிப்பு",
    "mode_farmer": "விவசாயி / குறுந்தொழில் முறை",
    "mode_farmer_subtitle": "எளிய உள்ளீடு",
    "mode_industry": "தொழில்துறை / ஆய்வக முறை",
    "mode_industry_subtitle": "மேம்பட்ட உயிர்வேதியியல் அளவீடு",
    "lbl_channel_a": "சேனல் ஏ: பயனர் விவரம் மற்றும் உணவு",
    "lbl_food_item": "உணவுப் பொருள்",
    "lbl_food_condition": "உணவு நிலை",
    "lbl_target_duration": "சேமிப்பு காலம் (நாட்கள்)",
    "lbl_storage_type": "சேமிப்பு வகை",
    "cond_raw": "பச்சை",
    "cond_fresh": "புதியது",
    "cond_fried": "வறுக்கப்பட்டது",
    "cond_processed": "பதப்படுத்தப்பட்டது",
    "store_ambient": "சாதாரண அறை வெப்பநிலை",
    "store_refrigerated": "குளிரூட்டப்பட்டது",
    "store_cold": "குளிர்பதனக் கிடங்கு",
    "food_strawberry": "ஸ்ட்ராபெரி (Strawberry)",
    "food_mango": "அல்போன்சா மாம்பழம்",
    "food_apple": "ஆப்பிள்",
    "food_tomato": "தக்காளி",
    "food_potato": "உருளைக்கிழங்கு",
    "food_potato_chips": "உருளைக்கிழங்கு சிப்ஸ்",
    "food_namkeen": "கார வகைகள் / நம்கீன்",
    "food_paneer": "பன்னீர் (Paneer)",
    "food_meat": "இறைச்சி",
    "food_other": "பிற புதிய காய்கறிகள்",
    "lbl_origin": "புறப்படும் இடம்",
    "lbl_destination": "சேருமிடம்",
    "lbl_transport_mode": "போக்குவரத்து முறை",
    "lbl_transit_days": "பயண நாட்கள்",
    "season_summer": "கோடைக்காலம்",
    "season_monsoon": "மழைக்காலம்",
    "season_winter": "குளிர்காலம்",
    "rec_title": "ஏஐ பரிந்துரைத்த பொதிவு",
    "rec_primary_sub": "முக்கிய தொழில்துறைப் பரிந்துரை",
    "rec_optimized_gauge": "உகந்த ஃபிலிம் தடிமன்",
    "rec_packaging_type": "பரிந்துரைக்கப்பட்ட பேக்கேஜிங்",
    "astm_title": "ASTM தரக் குறியீடுகள்",
    "card_shelf_life": "ஆயுள் நீட்டிப்பு",
    "card_sustainability": "சுற்றுச்சூழல் நிலைத்தன்மை மதிப்பீடு",
    "lbl_plastic_reduction": "பிளாஸ்டிக் பயன்பாட்டுக் குறைப்பு",
    "smart_insight_title": "ஏஐ அறிவார்ந்த வழிகாட்டல்"
})

# gu (Gujarati - ગુજરાતી)
translations["gu"] = make_lang_dict({
    "app_name": "પેકસેન્સ એઆઈ (PackSense AI)",
    "tagline": "સ્માર્ટ પેકેજિંગ • સ્વસ્થ આહાર • ઉજ્જવળ ભવિષ્ય",
    "nav_home": "મુખ્ય પૃષ્ઠ",
    "nav_workspace": "કાર્યસ્થળ (Workspace)",
    "nav_packaudit": "પેકઓડિટ (PackAudit)",
    "nav_history": "ઇતિહાસ",
    "nav_about": "અમારા વિશે",
    "nav_profile": "પ્રોફાઇલ",
    "nav_login": "લોગ ઇન",
    "nav_logout": "લોગ આઉટ",
    "nav_register": "નોંધણી કરો",
    "language_select": "ભાષા",
    "hero_title": "ખાદ્ય પેકેજિંગ માટે એઆઈ-આધારિત બુદ્ધિશાળી ભલામણ સિસ્ટમ",
    "hero_subtitle": "ખોરાકના ગુણધર્મો, પેકેજિંગ સ્થિતિ, હવામાન, પરિવહન અને પર્યાવરણીય સ્થિરતા પર આધારિત સ્માર્ટ ભલામણો.",
    "btn_start_analysis": "વિશ્લેષણ શરૂ કરો",
    "btn_packaudit": "પેકઓડિટ ચકાસો",
    "btn_learn_more": "વધુ જાણો",
    "btn_run_engine": "પેકસેન્સ એઆઈ ચલાવો",
    "btn_upload_image": "પેકેજિંગનો ફોટો અપલોડ કરો",
    "btn_switch_mode": "મોડ બદલો",
    "btn_save_pdf": "પીડીએફ ડાઉનલોડ કરો",
    "open_full_report": "સંપૂર્ણ ટેકનિકલ રિપોર્ટ ખોલો",
    "ready_to_optimize": "ઓપ્ટિમાઇઝેશન માટે તૈયાર",
    "ready_to_optimize_desc": "ડાબી બાજુના પેનલમાં પરિમાણો સેટ કરો અને 'પેકસેન્સ એઆઈ ચલાવો' પર ક્લિક કરો.",
    "formulation_ready": "ફોર્મ્યુલેશન તૈયાર છે",
    "extension_gain": "શેલ્ફ-લાઇફ વધારો",
    "mode_farmer": "ખેડૂત / લઘુ ઉદ્યોગ મોડ",
    "mode_farmer_subtitle": "સરળ અને સીધું ઇનપુટ",
    "mode_industry": "ઉદ્યોગ / પ્રયોગશાળા મોડ",
    "mode_industry_subtitle": "અદ્યતન બાયોકેમિકલ કેલિબ્રેશન",
    "lbl_channel_a": "ચેનલ એ: પ્રોફાઇલ અને ખોરાકની વિગતો",
    "lbl_food_item": "ખાદ્ય પદાર્થ",
    "lbl_food_condition": "ખોરાકની સ્થિતિ",
    "lbl_target_duration": "જરૂરી સંગ્રહ સમયગાળો (દિવસ)",
    "lbl_storage_type": "સંગ્રહ પ્રકાર",
    "cond_raw": "કાચું",
    "cond_fresh": "તાજું",
    "cond_fried": "તળેલું",
    "cond_processed": "પ્રોસેસ્ડ",
    "store_ambient": "સામાન્ય તાપમાન",
    "store_refrigerated": "રેફ્રિજરેટેડ",
    "store_cold": "કોલ્ડ સ્ટોરેજ",
    "food_strawberry": "સ્ટ્રોબેરી (Strawberry)",
    "food_mango": "હાફૂસ કેરી (Alphonso Mango)",
    "food_apple": "સફરજન",
    "food_tomato": "ટામેટાં",
    "food_potato": "બટાકા",
    "food_potato_chips": "બટાકાની વેફર્સ (ચિપ્સ)",
    "food_namkeen": "ફરસાણ / નમકીન",
    "food_paneer": "તાજું પનીર",
    "food_meat": "માંસ",
    "food_other": "અન્ય તાજા શાકભાજી",
    "lbl_origin": "શરૂઆતનું શહેર",
    "lbl_destination": "ગંતવ્ય શહેર",
    "lbl_transport_mode": "પરિવહનનું માધ્યમ",
    "lbl_transit_days": "પરિવહન દિવસો",
    "season_summer": "ઉનાળો",
    "season_monsoon": "ચોમાસું",
    "season_winter": "શિયાળો",
    "rec_title": "એઆઈ ભલામણ કરેલ પેકેજિંગ",
    "rec_primary_sub": "મુખ્ય ઔદ્યોગિક ભલામણ",
    "rec_optimized_gauge": "ઓપ્ટિમાઇઝ ફિલ્મ જાડાઈ",
    "rec_packaging_type": "ભલામણ કરેલ પેકેજિંગ પ્રકાર",
    "astm_title": "એએસટીએમ (ASTM) બેરિયર ધોરણો",
    "card_shelf_life": "શેલ્ફ-લાઇફ વિસ્તરણ",
    "card_sustainability": "પર્યાવરણીય સ્થિરતા સ્કોર",
    "lbl_plastic_reduction": "પ્લાસ્ટિક વપરાશમાં ઘટાડો",
    "smart_insight_title": "એઆઈ સ્માર્ટ માર્ગદર્શન અને સલાહ"
})

print("Generated all 21 languages! Total languages:", len(translations))

# Write out python file
with open("ai/translations.py", "w", encoding="utf-8") as f:
    f.write('"""\nPackSense AI - Complete 21-Language Localization Module\nSupports all 21 global and country languages.\n"""\n\n')
    f.write('SUPPORTED_LANGUAGES = ')
    f.write(json.dumps(SUPPORTED_LANGUAGES, ensure_ascii=False, indent=4))
    f.write('\n\nTRANSLATIONS = ')
    f.write(json.dumps(translations, ensure_ascii=False, indent=4))
    f.write("""

def get_translation(key, lang="en"):
    \"\"\"Fetches translation with fallback to English, then key itself.\"\"\"
    if not lang or lang not in TRANSLATIONS:
        lang = "en"
    lang_dict = TRANSLATIONS.get(lang, TRANSLATIONS.get("en", {}))
    val = lang_dict.get(key)
    if val:
        return val
    # Fallback to English
    return TRANSLATIONS.get("en", {}).get(key, key)
""")

print("Successfully written ai/translations.py")
