"""
PackSense AI - 21 Country Languages Localization Module
Comprehensive translations for 21 major agricultural & global export country languages.
Supports: English, Hindi, Marathi, Spanish, French, German, Chinese, Arabic, Portuguese,
Russian, Japanese, Italian, Turkish, Korean, Dutch, Vietnamese, Indonesian, Bengali,
Telugu, Tamil, and Gujarati.
"""

SUPPORTED_LANGUAGES = {
    "en": {"code": "en", "name": "English", "native": "English", "flag": "GB", "country": "United Kingdom"},
    "hi": {"code": "hi", "name": "Hindi", "native": "हिंदी", "flag": "IN", "country": "India"},
    "mr": {"code": "mr", "name": "Marathi", "native": "मराठी", "flag": "IN", "country": "India"},
    "gu": {"code": "gu", "name": "Gujarati", "native": "ગુજરાતી", "flag": "IN", "country": "India"},
    "bn": {"code": "bn", "name": "Bengali", "native": "বাংলা", "flag": "IN", "country": "India"},
    "te": {"code": "te", "name": "Telugu", "native": "తెలుగు", "flag": "IN", "country": "India"},
    "ta": {"code": "ta", "name": "Tamil", "native": "தமிழ்", "flag": "IN", "country": "India"},
    "es": {"code": "es", "name": "Spanish", "native": "Español", "flag": "ES", "country": "Spain"},
    "fr": {"code": "fr", "name": "French", "native": "Français", "flag": "FR", "country": "France"},
    "de": {"code": "de", "name": "German", "native": "Deutsch", "flag": "DE", "country": "Germany"},
    "zh": {"code": "zh", "name": "Chinese", "native": "中文", "flag": "CN", "country": "China"},
    "ar": {"code": "ar", "name": "Arabic", "native": "العربية", "flag": "SA", "country": "Saudi Arabia"},
    "pt": {"code": "pt", "name": "Portuguese", "native": "Português", "flag": "BR", "country": "Brazil"},
    "ru": {"code": "ru", "name": "Russian", "native": "Русский", "flag": "RU", "country": "Russia"},
    "ja": {"code": "ja", "name": "Japanese", "native": "日本語", "flag": "JP", "country": "Japan"},
    "it": {"code": "it", "name": "Italian", "native": "Italiano", "flag": "IT", "country": "Italy"},
    "tr": {"code": "tr", "name": "Turkish", "native": "Türkçe", "flag": "TR", "country": "Turkey"},
    "ko": {"code": "ko", "name": "Korean", "native": "한국어", "flag": "KR", "country": "South Korea"},
    "nl": {"code": "nl", "name": "Dutch", "native": "Nederlands", "flag": "NL", "country": "Netherlands"},
    "vi": {"code": "vi", "name": "Vietnamese", "native": "Tiếng Việt", "flag": "VN", "country": "Vietnam"},
    "id": {"code": "id", "name": "Indonesian", "native": "Bahasa Indonesia", "flag": "ID", "country": "Indonesia"}
}

# 1. Base English Translation Set
BASE_EN = {
    "app_name": "PackSense AI",
    "tagline": "Smart Packaging • Healthier Food • Brighter Tomorrow",
    "nav_home": "Home",
    "nav_workspace": "Workspace",
    "nav_packaudit": "PackAudit",
    "nav_history": "History",
    "nav_about": "About",
    "nav_profile": "Profile",
    "nav_login": "Login",
    "nav_logout": "Logout",
    "nav_register": "Register",
    "language_select": "Language",
    "history_records": "History Records",
    "view_history_log": "View History Log",
    "visual_analysis_title": "VISUAL PACKAGING ANALYSIS",
    "visual_analysis_subtitle": "Real-time visual packaging audit & AI optimization transformation",
    "live_visual_pipeline": "⚡ Live Visual Pipeline",
    "current_packaging": "Current Packaging",
    "existing_sample": "Existing Sample",
    "uploaded_sample_audit": "Uploaded Sample Audit",
    "uncalibrated_poly_pouch": "Uncalibrated Polyethylene Pouch",
    "single_layer_vulnerability": "Single-layer unsealed film with moisture vulnerability",
    "material_structure": "Material Structure",
    "barrier_grade": "Barrier Grade",
    "low_barrier_flawed": "Low Barrier (Flawed)",
    "shelf_life": "Shelf Life",
    "days": "Days",
    "vulnerability": "Vulnerability",
    "high_decay_risk": "High Decay Risk",
    "ai_optimization": "AI OPTIMIZATION",
    "astm_match_desc": "ASTM Barrier & Headspace Match",
    "ai_recommended": "AI Recommended",
    "optimized_solution": "Optimized Solution",
    "expected_shelf_life": "Expected Shelf Life",
    "packaging_unit_eco_score": "Packaging Unit Eco Score",
    "thickness_gauge": "Thickness Gauge",
    "estimated_unit_cost": "Estimated Unit Cost",
    "per_unit": "/ unit",
    "select_operational_mode": "SELECT OPERATIONAL MODE:",
    "mode_selector_hint": "Tailors recommendation complexity & terminology",
    "mode_farmer": "👨‍🌾 Farmer / SME Mode",
    "mode_farmer_subtitle": "Simple, practical guidelines, shelf life, cost & plain explanations",
    "mode_industry": "🔬 Industry / Lab Mode",
    "mode_industry_subtitle": "ASTM D3985 OTR, ASTM F1249 WVTR, MAP gas composition & polymer kinetics",
    "input_1_title": "Food / Product",
    "biochemical_profile": "Biochemical Profile",
    "lbl_selected_food": "Selected Food / Commodity *",
    "lbl_commodity_state": "Initial Commodity State",
    "opt_fresh": "Fresh Harvest (High Respiration)",
    "opt_raw": "Raw / Chilled Cut",
    "opt_fried": "Fried / Crisp (High Lipid Oxidation)",
    "opt_processed": "Processed / Pasteurized",
    "auto_spoilage_params": "Auto-Retrieved Spoilage Parameters:",
    "lbl_respiration": "Respiration:",
    "lbl_moisture_risk": "Moisture Risk:",
    "lbl_fat_vuln": "Fat Vulnerability:",
    "lbl_ethylene": "Ethylene:",
    "input_2_title": "Storage Duration",
    "calibrated_time_horizon": "Calibrated Time Horizon",
    "lbl_target_shelf_duration": "Target Shelf Duration Horizon *",
    "enter_duration_hint": "Enter the expected storage and transit lifespan:",
    "dur_years": "Years",
    "dur_months": "Months",
    "dur_weeks": "Weeks",
    "dur_days": "Days",
    "total_target_storage_duration": "Total Target Storage Duration:",
    "lbl_storage_temp_env": "Storage Temperature Environment",
    "opt_ambient": "Ambient (25°C - 35°C)",
    "opt_refrigerated": "Refrigerated (4°C - 8°C)",
    "opt_cold_storage": "Cold Storage Controlled (0°C - 4°C)",
    "input_3_title": "Packaging Image",
    "visual_audit_inspection": "Visual Audit Inspection",
    "lbl_upload_current_pack": "Upload Current Packaging Photo",
    "click_browse_photo": "Click to Browse or Take Photo",
    "file_types_hint": "PNG, JPG, WEBP up to 16MB",
    "input_4_title": "Origin → Destination",
    "transit_route": "Transit Route",
    "lbl_origin_city": "Origin City *",
    "lbl_dest_city": "Destination City *",
    "lbl_transport_mode": "Transportation Mode *",
    "opt_ambient_truck": "Ambient Open Truck (High Climate Stress)",
    "opt_reefer_truck": "Refrigerated Reefer Truck (Controlled Temp)",
    "opt_cold_chain": "Certified Cold Chain (Monitored Humidity & Temp)",
    "opt_rail_cargo": "Rail Freight Express",
    "lbl_estimated_transit_days": "Estimated Transit Days",
    "lbl_season": "Season",
    "opt_monsoon": "Monsoon (High Humidity)",
    "opt_summer": "Summer (High Heat)",
    "opt_winter": "Winter (Mild Ambient)",
    "lab_calibration": "LAB CALIBRATION",
    "advanced_biochem_overrides": "Advanced Biochemical Overrides",
    "lbl_initial_moisture": "Initial Moisture (%)",
    "lbl_free_fat": "Free Fat / Oil (%)",
    "lbl_manual_otr": "Manual OTR (cc/m²/day)",
    "lbl_manual_wvtr": "Manual WVTR (g/m²/day)",
    "btn_analyze": "✨ Analyze",
    "btn_start_analysis": "Start Analysis",
    "btn_packaudit": "PackAudit",
    "btn_learn_more": "Learn More",
    "btn_view": "View",
    "btn_delete": "Delete",
    "btn_save_analysis": "Save Analysis",
    "btn_export_pdf": "Print / Export Report",
    "ai_analysis_engine": "AI ANALYSIS ENGINE",
    "ai_engine_subtitle": "Multi-Factor Biochemical Spoilage & Packaging Synthesis",
    "calibrated_badge": "✓ CALIBRATED",
    "stage_biochem": "Biochemical Profiling",
    "stage_climate": "Climate Stress Mapping",
    "stage_barrier": "Barrier Calibration",
    "stage_packaging": "Packaging Match",
    "packaging_unit_sustainability": "🌱 Packaging Unit Sustainability",
    "packaging_unit_desc": "Calibrated specifically for the packaging container and film unit",
    "packaging_unit_evaluation": "PACKAGING UNIT EVALUATION",
    "eco_performance_rating": "Packaging Eco-Performance Rating",
    "factor_material_sustainability": "Material Sustainability",
    "factor_recyclability": "Recyclability / Biodegradability",
    "factor_material_quantity": "Material Quantity",
    "factor_barrier_efficiency": "Barrier Efficiency",
    "factor_environmental_impact": "Environmental Impact",
    "why_this_packaging": "WHY THIS PACKAGING?",
    "recommended_packaging": "RECOMMENDED PACKAGING",
    "estimated_packaging_cost": "Estimated Packaging Cost",
    "transport_advice_farmers": "🚛 Transportation & Storage Advice for Farmers",
    "technical_pack_spec": "TECHNICAL PACKAGING SPECIFICATION",
    "layering": "Layering:",
    "film_gauge_thickness": "Film Gauge / Thickness",
    "packaging_format": "Packaging Format",
    "otr_target_label": "ASTM D3985 OTR Target",
    "wvtr_target_label": "ASTM F1249 WVTR Target",
    "map_headspace_title": "Modified Atmosphere Packaging (MAP) Gas Headspace",
    "map_headspace_desc": "Calibrated to suppress respiration and aerobic microbial propagation.",
    "chemical_barrier_properties": "🔬 Chemical & Barrier Polymer Properties",
    "certified_bio_alternatives": "🌿 Certified Bio-Polymer Alternatives",
    "compostable_alternatives": "Compostable Alternatives",
    "current_vs_packsense": "Current Packaging vs PackSense Specification",
    "comp_parameter": "Parameter",
    "comp_current": "Current Baseline",
    "comp_recommended": "PackSense Recommendation",
    "comp_gain": "Gain / Impact",
    "ready_to_optimize": "Ready to Optimize",
    "ready_optimize_desc": "Select a commodity and storage duration on the left, then click \"✨ Analyze\" to calculate calibrated ASTM barrier targets, shelf life, and packaging unit sustainability.",
    "opt_history_title": "Optimization History (Browser LocalStorage)",
    "opt_history_subtitle": "All completed analyses are stored locally. Click any record to restore and inspect.",
    "btn_clear_history": "🗑️ Clear History",
    "hist_date_time": "Date & Time",
    "hist_food_product": "Food / Product",
    "hist_mode": "Mode",
    "hist_duration": "Storage Duration",
    "hist_corridor": "Corridor (Origin → Dest)",
    "hist_recommended_pack": "Recommended Packaging",
    "hist_sustainability_score": "Sustainability Score",
    "hist_action": "Action",
    "loading_history": "Loading history records..."
}

# 2. Hindi (India)
HI = {
    **BASE_EN,
    "app_name": "पैकसेंस एआई",
    "tagline": "स्मार्ट पैकेजिंग • सुरक्षित भोजन • उज्ज्वल कल",
    "nav_home": "होम",
    "nav_workspace": "कार्यक्षेत्र",
    "nav_packaudit": "पैकऑडिट",
    "nav_history": "इतिहास",
    "nav_about": "हमारे बारे में",
    "nav_profile": "प्रोफ़ाइल",
    "nav_login": "लॉग इन",
    "nav_logout": "लॉग आउट",
    "nav_register": "पंजीकरण",
    "language_select": "भाषा",
    "history_records": "इतिहास रिकॉर्ड",
    "view_history_log": "इतिहास लॉग देखें",
    "visual_analysis_title": "दृश्य पैकेजिंग विश्लेषण",
    "visual_analysis_subtitle": "वास्तविक समय दृश्य पैकेजिंग ऑडिट और एआई अनुकूलन परिवर्तन",
    "live_visual_pipeline": "⚡ लाइव विजुअल पाइपलाइन",
    "current_packaging": "वर्तमान पैकेजिंग",
    "existing_sample": "विद्यमान नमूना",
    "uploaded_sample_audit": "अपलोड किया गया नमूना ऑडिट",
    "uncalibrated_poly_pouch": "असंतुलित पॉलीथीन पाउच",
    "single_layer_vulnerability": "नमी संवेदनशीलता के साथ एकल परत बिना सील फिल्म",
    "material_structure": "सामग्री संरचना",
    "barrier_grade": "अवरोधक ग्रेड",
    "low_barrier_flawed": "कम अवरोधक (दोषपूर्ण)",
    "shelf_life": "शेल्फ जीवन",
    "days": "दिन",
    "vulnerability": "जोखिम संवेदनशीलता",
    "high_decay_risk": "उच्च सड़न जोखिम",
    "ai_optimization": "एआई अनुकूलन",
    "astm_match_desc": "एएसटीएम बैरियर व हेडस्पेस मिलान",
    "ai_recommended": "एआई अनुशंसित",
    "optimized_solution": "इष्टतम समाधान",
    "expected_shelf_life": "अपेक्षित शेल्फ जीवन",
    "packaging_unit_eco_score": "पैकेजिंग इको स्कोर",
    "thickness_gauge": "मोटाई गेज",
    "estimated_unit_cost": "अनुमानित यूनिट लागत",
    "per_unit": "/ इकाई",
    "select_operational_mode": "संचालन मोड चुनें:",
    "mode_selector_hint": "सुझावों की जटिलता और शब्दावली को अनुकूलित करता है",
    "mode_farmer": "👨‍🌾 किसान / लघु उद्योग मोड",
    "mode_farmer_subtitle": "सरल, व्यावहारिक दिशानिर्देश, शेल्फ जीवन, लागत व स्पष्ट विवरण",
    "mode_industry": "🔬 उद्योग / प्रयोगशाला मोड",
    "mode_industry_subtitle": "एएसटीएम डी३९८५ ओटीआर, डब्ल्यूवीटीआर व गैस संघटन विनिर्देश",
    "input_1_title": "खाद्य / उत्पाद",
    "biochemical_profile": "जैव रासायनिक प्रोफ़ाइल",
    "lbl_selected_food": "चयनित खाद्य / फसल *",
    "lbl_commodity_state": "प्रारंभिक खाद्य स्थिति",
    "opt_fresh": "ताज़ा फसल (उच्च श्वसन)",
    "opt_raw": "कच्चा / ठंडा कटा हुआ",
    "opt_fried": "तला हुआ / कुरकुरा (उच्च लिपिड ऑक्सीकरण)",
    "opt_processed": "संसाधित / पाश्चुरीकृत",
    "auto_spoilage_params": "स्वतः प्राप्त खराबी पैरामीटर:",
    "lbl_respiration": "श्वसन दर:",
    "lbl_moisture_risk": "नमी जोखिम:",
    "lbl_fat_vuln": "वसा संवेदनशीलता:",
    "lbl_ethylene": "एथिलीन:",
    "input_2_title": "भंडारण अवधि",
    "calibrated_time_horizon": "कैलिब्रेटेड समय सीमा",
    "lbl_target_shelf_duration": "लक्षित शेल्फ अवधि सीमा *",
    "enter_duration_hint": "अपेक्षित भंडारण और परिवहन जीवन दर्ज करें:",
    "dur_years": "वर्ष",
    "dur_months": "महीने",
    "dur_weeks": "सप्ताह",
    "dur_days": "दिन",
    "total_target_storage_duration": "कुल लक्षित भंडारण अवधि:",
    "lbl_storage_temp_env": "भंडारण तापमान वातावरण",
    "opt_ambient": "सामान्य परिवेश (25°C - 35°C)",
    "opt_refrigerated": "प्रशीतित (4°C - 8°C)",
    "opt_cold_storage": "नियंत्रित कोल्ड स्टोरेज (0°C - 4°C)",
    "input_3_title": "पैकेजिंग छवि",
    "visual_audit_inspection": "दृश्य ऑडिट निरीक्षण",
    "lbl_upload_current_pack": "वर्तमान पैकेजिंग फोटो अपलोड करें",
    "click_browse_photo": "फ़ाइल चुनने या फ़ोटो खींचने के लिए क्लिक करें",
    "file_types_hint": "PNG, JPG, WEBP (अधिकतम 16MB)",
    "input_4_title": "प्रस्थान शहर → गंतव्य शहर",
    "transit_route": "परिवहन मार्ग",
    "lbl_origin_city": "प्रस्थान शहर *",
    "lbl_dest_city": "गंतव्य शहर *",
    "lbl_transport_mode": "परिवहन साधन *",
    "opt_ambient_truck": "खुला ट्रक (उच्च मौसम तनाव)",
    "opt_reefer_truck": "रीफर प्रशीतित ट्रक (नियंत्रित तापमान)",
    "opt_cold_chain": "प्रमाणित कोल्ड चेन (निगरानी युक्त)",
    "opt_rail_cargo": "रेल माल ढुलाई एक्सप्रेस",
    "lbl_estimated_transit_days": "अनुमानित परिवहन दिन",
    "lbl_season": "मौसम",
    "opt_monsoon": "मानसून (उच्च आर्द्रता)",
    "opt_summer": "गर्मी (अत्यधिक तापमान)",
    "opt_winter": "सर्दी (सामान्य तापमान)",
    "lab_calibration": "प्रयोगशाला कैलिब्रेशन",
    "advanced_biochem_overrides": "उन्नत जैव रासायनिक मान",
    "lbl_initial_moisture": "प्रारंभिक नमी (%)",
    "lbl_free_fat": "मुक्त वसा / तेल (%)",
    "lbl_manual_otr": "कस्टम OTR (cc/m²/day)",
    "lbl_manual_wvtr": "कस्टम WVTR (g/m²/day)",
    "btn_analyze": "✨ विश्लेषण करें",
    "btn_start_analysis": "विश्लेषण शुरू करें",
    "btn_packaudit": "पैकऑडिट",
    "btn_save_analysis": "विश्लेषण सहेजें",
    "btn_export_pdf": "रिपोर्ट प्रिंट / निर्यात करें",
    "ai_analysis_engine": "एआई विश्लेषण इंजन",
    "ai_engine_subtitle": "बहु-कारक जैव रासायनिक विश्लेषण व पैकेजिंग संश्लेषण",
    "calibrated_badge": "✓ कैलिब्रेटेड",
    "stage_biochem": "जैव रासायनिक प्रोफाइलिंग",
    "stage_climate": "जलवायु तनाव मैपिंग",
    "stage_barrier": "बैरियर कैलिब्रेशन",
    "stage_packaging": "पैकेजिंग मिलान",
    "packaging_unit_sustainability": "🌱 पैकेजिंग इकाई स्थिरता",
    "packaging_unit_desc": "विशेष रूप से पैकेजिंग कंटेनर और फिल्म के लिए कैलिब्रेटेड",
    "packaging_unit_evaluation": "पैकेजिंग इकाई मूल्यांकन",
    "eco_performance_rating": "पैकेजिंग पर्यावरण प्रदर्शन रेटिंग",
    "factor_material_sustainability": "सामग्री स्थिरता",
    "factor_recyclability": "पुनर्चक्रण / बायोडिग्रेडेबिलिटी",
    "factor_material_quantity": "सामग्री की मात्रा",
    "factor_barrier_efficiency": "अवरोधक क्षमता",
    "factor_environmental_impact": "पर्यावरणीय प्रभाव",
    "why_this_packaging": "यही पैकेजिंग क्यों?",
    "recommended_packaging": "अनुशंसित पैकेजिंग",
    "estimated_packaging_cost": "अनुमानित पैकेजिंग लागत",
    "transport_advice_farmers": "🚛 किसानों के लिए परिवहन और भंडारण सलाह",
    "technical_pack_spec": "तकनीकी पैकेजिंग विनिर्देश",
    "layering": "परतें:",
    "film_gauge_thickness": "फिल्म मोटाई / गेज",
    "packaging_format": "पैकेजिंग प्रारूप",
    "otr_target_label": "ASTM D3985 OTR लक्ष्य",
    "wvtr_target_label": "ASTM F1249 WVTR लक्ष्य",
    "map_headspace_title": "संशोधित वायुमंडलीय पैकेजिंग (MAP) गैस हेडस्पेस",
    "map_headspace_desc": "श्वसन दर कम करने और सूक्ष्मजीव वृद्धि रोकने हेतु कैलिब्रेटेड।",
    "chemical_barrier_properties": "🔬 रासायनिक व बहुलक अवरोधक गुण",
    "certified_bio_alternatives": "🌿 प्रमाणित बायो-पॉलिमर विकल्प",
    "compostable_alternatives": "कम्पोस्टेबल विकल्प",
    "current_vs_packsense": "वर्तमान पैकेजिंग बनाम पैकसेंस विनिर्देश",
    "comp_parameter": "मापदंड",
    "comp_current": "वर्तमान आधार",
    "comp_recommended": "पैकसेंस अनुशंसा",
    "comp_gain": "सुधार / प्रभाव",
    "ready_to_optimize": "अनुकूलन के लिए तैयार",
    "ready_optimize_desc": "बाईं ओर कमोडिटी और भंडारण अवधि चुनें, फिर कैलिब्रेटेड बैरियर और शेल्फ जीवन की गणना के लिए \"✨ विश्लेषण करें\" पर क्लिक करें।",
    "opt_history_title": "अनुकूलन इतिहास (लोकल स्टोरेज)",
    "opt_history_subtitle": "सभी विश्लेषण स्थानीय रूप से सुरक्षित हैं। देखने के लिए किसी भी रिकॉर्ड पर क्लिक करें।",
    "btn_clear_history": "🗑️ इतिहास साफ करें",
    "hist_date_time": "दिनांक व समय",
    "hist_food_product": "खाद्य / उत्पाद",
    "hist_mode": "मोड",
    "hist_duration": "भंडारण अवधि",
    "hist_corridor": "मार्ग (प्रस्थान → गंतव्य)",
    "hist_recommended_pack": "अनुशंसित पैकेजिंग",
    "hist_sustainability_score": "इको स्कोर",
    "hist_action": "क्रिया",
    "loading_history": "इतिहास रिकॉर्ड लोड हो रहे हैं..."
}

# 3. Marathi (India)
MR = {
    **BASE_EN,
    "app_name": "पॅकसेन्स एआय",
    "tagline": "स्मार्ट पॅकेजिंग • निरोगी अन्न • उज्वल भविष्य",
    "nav_home": "मुख्यपृष्ठ",
    "nav_workspace": "कार्यक्षेत्र",
    "nav_packaudit": "पॅकऑडिट",
    "nav_history": "इतिहास",
    "nav_about": "आमच्याबद्दल",
    "nav_profile": "प्रोफाइल",
    "nav_login": "लॉग इन",
    "nav_logout": "लॉग आउट",
    "nav_register": "नोंदणी",
    "language_select": "भाषा",
    "history_records": "इतिहास नोंदी",
    "view_history_log": "इतिहास लॉग पहा",
    "visual_analysis_title": "व्हिज्युअल पॅकेजिंग विश्लेषण",
    "visual_analysis_subtitle": "थेट पॅकेजिंग ऑडिट व एआय ऑप्टिमायझेशन रूपांतरण",
    "live_visual_pipeline": "⚡ थेट व्हिज्युअल पाइपलाइन",
    "current_packaging": "सध्याचे पॅकेजिंग",
    "existing_sample": "विद्यमान नमुना",
    "uploaded_sample_audit": "अपलोड केलेला नमुना ऑडिट",
    "uncalibrated_poly_pouch": "असंतुलित पॉलिथिलीन पाऊच",
    "single_layer_vulnerability": "ओलाव्यापासून असुरक्षित सिंगल-लेअर फिल्म",
    "material_structure": "साहित्य रचना",
    "barrier_grade": "अवरोधक श्रेणी",
    "low_barrier_flawed": "कमी अवरोधक (दोषपूर्ण)",
    "shelf_life": "साठवणूक आयुष्य",
    "days": "दिवस",
    "vulnerability": "जोखीम पातळी",
    "high_decay_risk": "उच्च नासाडी जोखीम",
    "ai_optimization": "एआय ऑप्टिमायझेशन",
    "astm_match_desc": "एएसटीएम बॅरियर व हेडस्पेस जुळवणी",
    "ai_recommended": "एआय शिफारस केलेले",
    "optimized_solution": "इष्टतम उपाय",
    "expected_shelf_life": "अपेक्षित साठवणूक आयुष्य",
    "packaging_unit_eco_score": "पॅकेजिंग इको स्कोअर",
    "thickness_gauge": "जाडी गेज",
    "estimated_unit_cost": "अंदाजे युनिट खर्च",
    "per_unit": "/ युनिट",
    "select_operational_mode": "कार्यप्रणाली मोड निवडा:",
    "mode_selector_hint": "शिफारशींची भाषा आणि तांत्रिक तपशील सानुकूलित करतो",
    "mode_farmer": "👨‍🌾 शेतकरी / लघु उद्योग मोड",
    "mode_farmer_subtitle": "साधे, व्यावहारिक मार्गदर्शन, साठवणूक आयुष्य, खर्च व स्पष्ट माहिती",
    "mode_industry": "🔬 उद्योग / प्रयोगशाळा मोड",
    "mode_industry_subtitle": "एएसटीएम डी३९८५ ओटीआर, डब्ल्यूव्हीटीआर व एमएपी गॅस घटक",
    "input_1_title": "अन्न / उत्पादन",
    "biochemical_profile": "जैवरासायनिक प्रोफाइल",
    "lbl_selected_food": "निवडलेले अन्न / पीक *",
    "lbl_commodity_state": "सुरुवातीची स्थिती",
    "opt_fresh": "ताजी काढणी (उच्च श्वसन)",
    "opt_raw": "कच्चे / कापलेले",
    "opt_fried": "तळलेले / कुरकुरीत (उच्च लिपिड ऑक्सिडेशन)",
    "opt_processed": "प्रक्रिया केलेले / पाश्चराइज्ड",
    "auto_spoilage_params": "आपोआप मिळालेले निकष:",
    "lbl_respiration": "श्वसन दर:",
    "lbl_moisture_risk": "ओलावा जोखीम:",
    "lbl_fat_vuln": "चरबी संवेदनशीलता:",
    "lbl_ethylene": "इथिलीन:",
    "input_2_title": "साठवणूक कालावधी",
    "calibrated_time_horizon": "नियोजित कालावधी",
    "lbl_target_shelf_duration": "लक्ष्य साठवणूक कालावधी *",
    "enter_duration_hint": "अपेक्षित साठवणूक व वाहतूक कालावधी नोंदवा:",
    "dur_years": "वर्षे",
    "dur_months": "महिने",
    "dur_weeks": "आठवडे",
    "dur_days": "दिवस",
    "total_target_storage_duration": "एकूण लक्ष्य साठवणूक कालावधी:",
    "lbl_storage_temp_env": "साठवणूक तापमान वातावरण",
    "opt_ambient": "साधारण तापमान (25°C - 35°C)",
    "opt_refrigerated": "शीतकरण (4°C - 8°C)",
    "opt_cold_storage": "नियंत्रित कोल्ड स्टोरेज (0°C - 4°C)",
    "input_3_title": "पॅकेजिंग छायाचित्र",
    "visual_audit_inspection": "व्हिज्युअल ऑडिट तपासणी",
    "lbl_upload_current_pack": "सध्याच्या पॅकेजिंगचे छायाचित्र अपलोड करा",
    "click_browse_photo": "फोटो निवडण्यासाठी किंवा काढण्यासाठी क्लिक करा",
    "file_types_hint": "PNG, JPG, WEBP (कमाल 16MB)",
    "input_4_title": "मूळ शहर → गंतव्य शहर",
    "transit_route": "वाहतूक मार्ग",
    "lbl_origin_city": "मूळ शहर *",
    "lbl_dest_city": "गंतव्य शहर *",
    "lbl_transport_mode": "वाहतूक प्रकार *",
    "opt_ambient_truck": "खुला ट्रक (उच्च हवामान ताण)",
    "opt_reefer_truck": "प्रशीतित रीफर ट्रक (नियंत्रित तापमान)",
    "opt_cold_chain": "प्रमाणित कोल्ड चेन (तापमान नियंत्रित)",
    "opt_rail_cargo": "रेल्वे मालवाहतूक एक्सप्रेस",
    "lbl_estimated_transit_days": "अंदाजे प्रवासाचे दिवस",
    "lbl_season": "ऋतू",
    "opt_monsoon": "पावसाळा (जास्त आर्द्रता)",
    "opt_summer": "उन्हाळा (जास्त उष्णता)",
    "opt_winter": "हिवाळा (कमी तापमान)",
    "lab_calibration": "प्रयोगशाळा कॅलिब्रेशन",
    "advanced_biochem_overrides": "प्रगत जैवरासायनिक मूल्ये",
    "lbl_initial_moisture": "प्रारंभिक ओलावा (%)",
    "lbl_free_fat": "चरबी / तेल प्रमाण (%)",
    "lbl_manual_otr": "मॅन्युअल OTR (cc/m²/day)",
    "lbl_manual_wvtr": "मॅन्युअल WVTR (g/m²/day)",
    "btn_analyze": "✨ विश्लेषण करा",
    "btn_start_analysis": "विश्लेषण सुरू करा",
    "btn_packaudit": "पॅकऑडिट",
    "btn_save_analysis": "विश्लेषण सेव्ह करा",
    "btn_export_pdf": "अहवाल प्रिंट / डाउनलोड करा",
    "ai_analysis_engine": "एआय विश्लेषण इंजिन",
    "ai_engine_subtitle": "अनेक घटकांवर आधारित जैवरासायनिक विश्लेषण व पॅकेजिंग संश्लेषण",
    "calibrated_badge": "✓ कॅलिब्रेटेड",
    "stage_biochem": "जैवरासायनिक विश्लेषण",
    "stage_climate": "हवामान ताण मॅपिंग",
    "stage_barrier": "अवरोधक क्षमता निर्धारण",
    "stage_packaging": "पॅकेजिंग जुळवणी",
    "packaging_unit_sustainability": "🌱 पॅकेजिंग युनिट शाश्वतता",
    "packaging_unit_desc": "पॅकेजिंग कंटेनर व फिल्मसाठी विशेष कॅलिब्रेटेड",
    "packaging_unit_evaluation": "पॅकेजिंग युनिट मूल्यमापन",
    "eco_performance_rating": "पॅकेजिंग पर्यावरण कामगिरी रेटिंग",
    "factor_material_sustainability": "साहित्य शाश्वतता",
    "factor_recyclability": "पुनर्चक्रण / विघटनक्षमता",
    "factor_material_quantity": "साहित्याचे प्रमाण",
    "factor_barrier_efficiency": "अवरोधक कार्यक्षमता",
    "factor_environmental_impact": "पर्यावरणीय प्रभाव",
    "why_this_packaging": "हेच पॅकेजिंग का?",
    "recommended_packaging": "शिफारस केलेले पॅकेजिंग",
    "estimated_packaging_cost": "अंदाजे पॅकेजिंग खर्च",
    "transport_advice_farmers": "🚛 शेतकऱ्यांसाठी वाहतूक व साठवणूक सल्ला",
    "technical_pack_spec": "तांत्रिक पॅकेजिंग तपशील",
    "layering": "थर रचना:",
    "film_gauge_thickness": "फिल्म जाडी / गेज",
    "packaging_format": "पॅकेजिंग स्वरूप",
    "otr_target_label": "ASTM D3985 OTR लक्ष्य",
    "wvtr_target_label": "ASTM F1249 WVTR लक्ष्य",
    "map_headspace_title": "सुधारित वातावरण पॅकेजिंग (MAP) गॅस मिश्रण",
    "map_headspace_desc": "श्वसन दर कमी करण्यासाठी व जिवाणूंची वाढ रोखण्यासाठी कॅलिब्रेटेड.",
    "chemical_barrier_properties": "🔬 रासायनिक व पॉलिमर गुणधर्म",
    "certified_bio_alternatives": "🌿 प्रमाणित बायो-पॉलिमर पर्याय",
    "compostable_alternatives": "कंपोस्टेबल पर्याय",
    "current_vs_packsense": "सध्याचे पॅकेजिंग विरूद्ध पॅकसेन्स तपशील",
    "comp_parameter": "घटक",
    "comp_current": "सध्याची स्थिती",
    "comp_recommended": "पॅकसेन्स शिफारस",
    "comp_gain": "सुधारणा / फायदा",
    "ready_to_optimize": "विश्लेषणासाठी सज्ज",
    "ready_optimize_desc": "डावीकडे उत्पादन आणि साठवणूक कालावधी निवडा, नंतर अचूक बॅरियर व टिकवण क्षमता मोजण्यासाठी \"✨ विश्लेषण करा\" वर क्लिक करा.",
    "opt_history_title": "ऑप्टिमायझेशन इतिहास (ब्राउझर लोकल स्टोरेज)",
    "opt_history_subtitle": "सर्व पूर्ण झालेले विश्लेषण सुरक्षित आहेत. पूर्ववत करण्यासाठी कोणत्याही नोंदीवर क्लिक करा.",
    "btn_clear_history": "🗑️ इतिहास साफ करा",
    "hist_date_time": "तारीख व वेळ",
    "hist_food_product": "अन्न / उत्पादन",
    "hist_mode": "मोड",
    "hist_duration": "साठवणूक कालावधी",
    "hist_corridor": "मार्ग (मूळ → गंतव्य)",
    "hist_recommended_pack": "शिफारस केलेले पॅकेजिंग",
    "hist_sustainability_score": "इको स्कोअर",
    "hist_action": "कृती",
    "loading_history": "इतिहास नोंदी लोड होत आहेत..."
}

# 4. Gujarati (India)
GU = {
    **BASE_EN,
    "app_name": "પૅકસેન્સ એઆઈ",
    "tagline": "સ્માર્ટ પેકેજિંગ • તંદુરસ્ત ખોરાક • ઉજ્જવળ ભવિષ્ય",
    "nav_home": "હોમ",
    "nav_workspace": "કાર્યસ્થળ",
    "nav_packaudit": "પૅકઓડિટ",
    "nav_history": "ઇતિહાસ",
    "nav_about": "અમારા વિશે",
    "nav_profile": "પ્રોફાઇલ",
    "nav_login": "લૉગિન",
    "nav_logout": "લૉગઆઉટ",
    "nav_register": "નોંધણી",
    "language_select": "ભાષા",
    "history_records": "ઇતિહાસ રેકોર્ડ",
    "view_history_log": "ઇતિહાસ લોગ જુઓ",
    "visual_analysis_title": "વિઝ્યુઅલ પેકેજિંગ વિશ્લેષણ",
    "visual_analysis_subtitle": "રીઅલ-ટાઇમ વિઝ્યુઅલ પેકેજિંગ ઓડિટ અને એઆઈ ઓપ્ટિમાઇઝેશન",
    "live_visual_pipeline": "⚡ લાઇવ વિઝ્યુઅલ પાઇપલાઇન",
    "current_packaging": "વર્તમાન પેકેજિંગ",
    "existing_sample": "હાલનો નમૂનો",
    "material_structure": "સામગ્રીનું માળખું",
    "barrier_grade": "બેરિયર ગ્રેડ",
    "shelf_life": "શેલ્ફ લાઇફ",
    "days": "દિવસો",
    "vulnerability": "જોખમ સ્તર",
    "ai_recommended": "એઆઈ ભલામણ કરેલ",
    "optimized_solution": "શ્રેષ્ઠ ઉકેલ",
    "expected_shelf_life": "અપેક્ષિત શેલ્ફ લાઇફ",
    "packaging_unit_eco_score": "પેકેજિંગ ઇકો સ્કોર",
    "thickness_gauge": "જાડાઈ ગેજ",
    "estimated_unit_cost": "અંદાજિત એકમ ખર્ચ",
    "per_unit": "/ એકમ",
    "select_operational_mode": "ઓપરેશનલ મોડ પસંદ કરો:",
    "mode_farmer": "👨‍🌾 ખેડૂત / એસએમઈ મોડ",
    "mode_farmer_subtitle": "સરળ માર્ગદર્શિકા, શેલ્ફ લાઇફ, ખર્ચ અને વ્યવહારુ માહિતી",
    "mode_industry": "🔬 ઉદ્યોગ / પ્રયોગશાળા મોડ",
    "mode_industry_subtitle": "ASTM D3985 OTR, WVTR અને MAP ગેસ વિશિષ્ટતાઓ",
    "input_1_title": "ખોરાક / ઉત્પાદન",
    "lbl_selected_food": "પસંદ કરેલ ખોરાક / પાક *",
    "lbl_commodity_state": "પ્રારંભિક સ્થિતિ",
    "input_2_title": "સંગ્રહ સમયગાળો",
    "dur_years": "વર્ષ",
    "dur_months": "મહિના",
    "dur_weeks": "અઠવાડિયા",
    "dur_days": "દિવસ",
    "total_target_storage_duration": "કુલ લક્ષ્ય સંગ્રહ સમયગાળો:",
    "input_3_title": "પેકેજિંગ ફોટો",
    "click_browse_photo": "ફોટો પસંદ કરવા અથવા ક્લિક કરવા માટે દબાવો",
    "input_4_title": "મૂળ શહેર → ગંતવ્ય શહેર",
    "lbl_origin_city": "મૂળ શહેર *",
    "lbl_dest_city": "ગંતવ્ય શહેર *",
    "lbl_transport_mode": "વાહનવ્યવહાર મોડ *",
    "btn_analyze": "✨ વિશ્લેષણ કરો",
    "ai_analysis_engine": "એઆઈ વિશ્લેષણ એન્જિન",
    "why_this_packaging": "આ પેકેજિંગ શા માટે?",
    "recommended_packaging": "ભલામણ કરેલ પેકેજિંગ",
    "transport_advice_farmers": "🚛 ખેડૂતો માટે પરિવહન અને સંગ્રહ સલાહ",
    "opt_history_title": "ઑપ્ટિમાઇઝેશન ઇતિહાસ",
    "btn_clear_history": "🗑️ ઇતિહાસ સાફ કરો"
}

# 5. Bengali (India / Bangladesh)
BN = {
    **BASE_EN,
    "app_name": "প্যাকসেন্স এআই",
    "tagline": "স্মার্ট প্যাকেজিং • স্বাস্থ্যকর খাদ্য • উজ্জ্বল ভবিষ্যৎ",
    "nav_home": "হোম",
    "nav_workspace": "ওয়ার্কস্পেস",
    "nav_packaudit": "প্যাকঅডিট",
    "nav_history": "ইতিহাস",
    "nav_about": "সম্পর্কে",
    "nav_profile": "প্রোফাইল",
    "nav_login": "লগইন",
    "nav_logout": "লগআউট",
    "nav_register": "নিবন্ধন",
    "language_select": "ভাষা",
    "history_records": "ইতিহাস রেকর্ড",
    "view_history_log": "ইতিহাস লগ দেখুন",
    "visual_analysis_title": "ভিজ্যুয়াল প্যাকেজিং বিশ্লেষণ",
    "visual_analysis_subtitle": "রিয়েল-টাইম প্যাকেজিং অডিট ও এআই অপ্টিমাইজেশন",
    "current_packaging": "বর্তমান প্যাকেজিং",
    "existing_sample": "বিদ্যমান নমুনা",
    "material_structure": "উপাদান কাঠামো",
    "barrier_grade": "ব্যারিয়ার গ্রেড",
    "shelf_life": "সংরক্ষণের মেয়াদ",
    "days": "দিন",
    "ai_recommended": "এআই প্রস্তাবিত প্যাকেজিং",
    "optimized_solution": "অপ্টিমাইজড সমাধান",
    "expected_shelf_life": "প্রত্যাশিত মেয়াদ",
    "packaging_unit_eco_score": "ইকো স্কোর",
    "mode_farmer": "👨‍🌾 কৃষক / ক্ষুদ্র শিল্প মোড",
    "mode_farmer_subtitle": "সহজ ব্যবহারিক পরামর্শ, মেয়াদ ও খরচ",
    "mode_industry": "🔬 শিল্প / ল্যাব মোড",
    "mode_industry_subtitle": "ASTM D3985 OTR, WVTR এবং MAP গ্যাস বিশ্লেষণ",
    "lbl_selected_food": "নির্বাচিত খাদ্যদ্রব্য *",
    "btn_analyze": "✨ বিশ্লেষণ করুন",
    "why_this_packaging": "কেন এই প্যাকেজিং?",
    "recommended_packaging": "প্রস্তাবিত প্যাকেজিং",
    "transport_advice_farmers": "🚛 কৃষকদের জন্য পরিবহন ও সংরক্ষণ পরামর্শ",
    "btn_clear_history": "🗑️ ইতিহাস মুছুন"
}

# 6. Telugu (India)
TE = {
    **BASE_EN,
    "app_name": "ప్యాక్‌సెన్స్ AI",
    "tagline": "స్మార్ట్ ప్యాకేజింగ్ • ఆరోగ్యకరమైన ఆహారం • ఉజ్వల భవిష్యత్తు",
    "nav_home": "హోమ్",
    "nav_workspace": "వర్క్‌స్పేస్",
    "nav_packaudit": "ప్యాక్ ఆడిట్",
    "nav_history": "చరిత్ర",
    "nav_about": "గురించి",
    "language_select": "భాష",
    "visual_analysis_title": "విజువల్ ప్యాకేజింగ్ విశ్లేషణ",
    "current_packaging": "ప్రస్తుత ప్యాకేజింగ్",
    "shelf_life": "నిల్వ కాలం",
    "days": "రోజులు",
    "ai_recommended": "AI సిఫార్సు చేసిన ప్యాకేజింగ్",
    "mode_farmer": "👨‍🌾 రైతు / SME మోడ్",
    "mode_farmer_subtitle": "సులభమైన సూచనలు, నిల్వ కాలం మరియు ఖర్చు",
    "mode_industry": "🔬 పరిశ్రమ / ల్యాబ్ మోడ్",
    "lbl_selected_food": "ఎంచుకున్న ఆహార పదార్ధం *",
    "btn_analyze": "✨ విశ్లేషించండి",
    "why_this_packaging": "ఈ ప్యాకేజింగ్ ఎందుకు?",
    "recommended_packaging": "సిఫార్సు చేయబడిన ప్యాకేజింగ్",
    "transport_advice_farmers": "🚛 రైతుల కోసం రవాణా & నిల్వ సలహా",
    "btn_clear_history": "🗑️ చరిత్రను క్లియర్ చేయండి"
}

# 7. Tamil (India)
TA = {
    **BASE_EN,
    "app_name": "பேக்சென்ஸ் AI",
    "tagline": "ஸ்மார்ட் பேக்கேஜிங் • ஆரோக்கியமான உணவு • சிறந்த எதிர்காலம்",
    "nav_home": "முகப்பு",
    "nav_workspace": "பணியிடம்",
    "nav_packaudit": "பேக் தணிக்கை",
    "nav_history": "வரலாறு",
    "nav_about": "பற்றி",
    "language_select": "மொழி",
    "visual_analysis_title": "காட்சி பேக்கேஜிங் பகுப்பாய்வு",
    "current_packaging": "தற்போதைய பேக்கேஜிங்",
    "shelf_life": "சேமிப்பு காலம்",
    "days": "நாட்கள்",
    "ai_recommended": "AI பரிந்துரைக்கப்பட்ட பேக்கேஜிங்",
    "mode_farmer": "👨‍🌾 விவசாயி / SME பயன்முறை",
    "mode_farmer_subtitle": "எளிய நடைமுறை வழிகாட்டுதல்கள் மற்றும் செலவு",
    "mode_industry": "🔬 தொழில் / ஆய்வக பயன்முறை",
    "lbl_selected_food": "தேர்ந்தெடுக்கப்பட்ட உணவுப்பொருள் *",
    "btn_analyze": "✨ பகுப்பாய்வு செய்",
    "why_this_packaging": "இந்த பேக்கேஜிங் ஏன்?",
    "recommended_packaging": "பரிந்துரைக்கப்பட்ட பேக்கேஜிங்",
    "transport_advice_farmers": "🚛 விவசாயிகளுக்கான போக்குவரத்து மற்றும் சேமிப்பு ஆலோசனை",
    "btn_clear_history": "🗑️ வரலாற்றை அழிக்கவும்"
}

# 8. Spanish (Spain / Latin America)
ES = {
    **BASE_EN,
    "app_name": "PackSense AI",
    "tagline": "Envasado Inteligente • Alimentos Seguros • Futuro Sostenible",
    "nav_home": "Inicio",
    "nav_workspace": "Espacio de Trabajo",
    "nav_packaudit": "Auditoría Visual",
    "nav_history": "Historial",
    "nav_about": "Acerca de",
    "nav_profile": "Perfil",
    "nav_login": "Iniciar Sesión",
    "nav_logout": "Cerrar Sesión",
    "nav_register": "Registrarse",
    "language_select": "Idioma",
    "history_records": "Registros Históricos",
    "view_history_log": "Ver Historial",
    "visual_analysis_title": "ANÁLISIS VISUAL DE ENVASADO",
    "visual_analysis_subtitle": "Auditoría visual de envases y optimización con IA en tiempo real",
    "live_visual_pipeline": "⚡ Canal Visual en Directo",
    "current_packaging": "Envase Actual",
    "existing_sample": "Muestra Existente",
    "material_structure": "Estructura del Material",
    "barrier_grade": "Grado de Barrera",
    "low_barrier_flawed": "Barrera Baja (Defectuosa)",
    "shelf_life": "Vida Útil",
    "days": "Días",
    "vulnerability": "Vulnerabilidad",
    "high_decay_risk": "Alto Riesgo de Deterioro",
    "ai_optimization": "OPTIMIZACIÓN IA",
    "ai_recommended": "Recomendado por IA",
    "optimized_solution": "Solución Optimizada",
    "expected_shelf_life": "Vida Útil Esperada",
    "packaging_unit_eco_score": "Puntuación Ecológica",
    "thickness_gauge": "Calibre / Grosor",
    "estimated_unit_cost": "Coste Unitario Estimado",
    "per_unit": "/ unidad",
    "select_operational_mode": "SELECCIONAR MODO OPERATIVO:",
    "mode_farmer": "👨‍🌾 Modo Agricultor / PYME",
    "mode_farmer_subtitle": "Pautas prácticas sencillas, vida útil, costes y explicaciones claras",
    "mode_industry": "🔬 Modo Industria / Laboratorio",
    "mode_industry_subtitle": "Normas ASTM D3985 OTR, ASTM F1249 WVTR y cinética polimérica",
    "input_1_title": "Alimento / Producto",
    "biochemical_profile": "Perfil Bioquímico",
    "lbl_selected_food": "Alimento / Producto Seleccionado *",
    "lbl_commodity_state": "Estado Inicial del Producto",
    "opt_fresh": "Cosecha Fresca (Alta Respiración)",
    "opt_raw": "Crudo / Cortado Refrigerado",
    "opt_fried": "Frito / Crujiente (Alta Oxidación)",
    "opt_processed": "Procesado / Pasteurizado",
    "input_2_title": "Duración de Almacenamiento",
    "dur_years": "Años",
    "dur_months": "Meses",
    "dur_weeks": "Semanas",
    "dur_days": "Días",
    "total_target_storage_duration": "Duración Total de Almacenamiento:",
    "input_3_title": "Foto del Envase",
    "click_browse_photo": "Haga clic para buscar o tomar foto",
    "input_4_title": "Origen → Destino",
    "transit_route": "Ruta de Tránsito",
    "lbl_origin_city": "Ciudad de Origen *",
    "lbl_dest_city": "Ciudad de Destino *",
    "lbl_transport_mode": "Modo de Transporte *",
    "btn_analyze": "✨ Analizar",
    "ai_analysis_engine": "MOTOR DE ANÁLISIS IA",
    "packaging_unit_sustainability": "🌱 Sostenibilidad de la Unidad de Envasado",
    "why_this_packaging": "¿POR QUÉ ESTE ENVASE?",
    "recommended_packaging": "ENVASE RECOMENDADO",
    "estimated_packaging_cost": "Coste Estimado del Envase",
    "transport_advice_farmers": "🚛 Consejos de Transporte y Almacenamiento para Agricultores",
    "technical_pack_spec": "ESPECIFICACIÓN TÉCNICA DE ENVASADO",
    "current_vs_packsense": "Envase Actual frente a Especificación PackSense",
    "opt_history_title": "Historial de Optimizaciones (LocalStorage)",
    "btn_clear_history": "🗑️ Borrar Historial"
}

# 9. French (France)
FR = {
    **BASE_EN,
    "app_name": "PackSense AI",
    "tagline": "Emballage Intelligent • Aliments Sains • Avenir Durable",
    "nav_home": "Accueil",
    "nav_workspace": "Espace Travail",
    "nav_packaudit": "PackAudit",
    "nav_history": "Historique",
    "nav_about": "À Propos",
    "language_select": "Langue",
    "visual_analysis_title": "ANALYSE VISUELLE DE L'EMBALLAGE",
    "visual_analysis_subtitle": "Audit visuel et optimisation IA de l'emballage en temps réel",
    "current_packaging": "Emballage Actuel",
    "existing_sample": "Échantillon Existant",
    "material_structure": "Structure du Matériau",
    "barrier_grade": "Niveau de Barrière",
    "shelf_life": "Durée de Conservation",
    "days": "Jours",
    "ai_recommended": "Recommandé par l'IA",
    "optimized_solution": "Solution Optimisée",
    "expected_shelf_life": "Durée de Vie Estimée",
    "packaging_unit_eco_score": "Score Écologique",
    "mode_farmer": "👨‍🌾 Mode Agriculteur / PME",
    "mode_farmer_subtitle": "Conseils pratiques simples, durée de vie et coûts",
    "mode_industry": "🔬 Mode Industrie / Labo",
    "mode_industry_subtitle": "Normes ASTM OTR, WVTR et atmosphère modifiée MAP",
    "lbl_selected_food": "Denrée / Produit Sélectionné *",
    "btn_analyze": "✨ Analyser",
    "why_this_packaging": "POURQUOI CET EMBALLAGE ?",
    "recommended_packaging": "EMBALLAGE RECOMMANDÉ",
    "transport_advice_farmers": "🚛 Conseils de Transport et de Stockage pour Agriculteurs",
    "btn_clear_history": "🗑️ Effacer l'Historique"
}

# 10. German (Germany)
DE = {
    **BASE_EN,
    "app_name": "PackSense AI",
    "tagline": "Intelligente Verpackung • Gesunde Lebensmittel • Grüne Zukunft",
    "nav_home": "Startseite",
    "nav_workspace": "Arbeitsbereich",
    "nav_packaudit": "PackAudit",
    "nav_history": "Verlauf",
    "nav_about": "Über uns",
    "language_select": "Sprache",
    "visual_analysis_title": "VISUELLE VERPACKUNGSANALYSE",
    "visual_analysis_subtitle": "Echtzeit-Verpackungsaudit und KI-Optimierung",
    "current_packaging": "Aktuelle Verpackung",
    "material_structure": "Materialstruktur",
    "barrier_grade": "Barrieregrad",
    "shelf_life": "Haltbarkeit",
    "days": "Tage",
    "ai_recommended": "KI-Empfehlung",
    "expected_shelf_life": "Erwartete Haltbarkeit",
    "packaging_unit_eco_score": "Öko-Punktzahl",
    "mode_farmer": "👨‍🌾 Landwirt / KMU-Modus",
    "mode_farmer_subtitle": "Praktische Richtlinien, Haltbarkeit und Kosten",
    "mode_industry": "🔬 Industrie / Labor-Modus",
    "mode_industry_subtitle": "ASTM D3985 OTR, WVTR und MAP-Gaszusammensetzung",
    "lbl_selected_food": "Ausgewähltes Lebensmittel *",
    "btn_analyze": "✨ Analysieren",
    "why_this_packaging": "WARUM DIESE VERPACKUNG?",
    "recommended_packaging": "EMPFOHLENE VERPACKUNG",
    "transport_advice_farmers": "🚛 Transport- und Lagerungshinweise für Landwirte",
    "btn_clear_history": "🗑️ Verlauf Löschen"
}

# 11. Mandarin Chinese (China)
ZH = {
    **BASE_EN,
    "app_name": "PackSense AI",
    "tagline": "智能包装 • 健康食品 • 绿色未来",
    "nav_home": "首页",
    "nav_workspace": "工作区",
    "nav_packaudit": "包装审计",
    "nav_history": "历史记录",
    "nav_about": "关于系统",
    "language_select": "语言",
    "visual_analysis_title": "视觉包装智能分析",
    "visual_analysis_subtitle": "实时视觉包装检测与AI保鲜优化转换",
    "current_packaging": "当前包装",
    "existing_sample": "现有样本",
    "material_structure": "材料结构",
    "barrier_grade": "阻隔等级",
    "shelf_life": "保质期",
    "days": "天",
    "vulnerability": "易腐风险",
    "ai_recommended": "AI推荐包装",
    "optimized_solution": "优化方案",
    "expected_shelf_life": "预期保鲜期",
    "packaging_unit_eco_score": "包装环保评分",
    "thickness_gauge": "厚度规格",
    "estimated_unit_cost": "预估单价",
    "per_unit": "/ 件",
    "select_operational_mode": "选择工作模式：",
    "mode_farmer": "👨‍🌾 农户 / 中小企业模式",
    "mode_farmer_subtitle": "通俗易懂的实用指南、保鲜期与成本核算",
    "mode_industry": "🔬 工业 / 实验室模式",
    "mode_industry_subtitle": "ASTM D3985 透氧率、透湿率与气调保鲜参数",
    "input_1_title": "食品 / 农产品",
    "lbl_selected_food": "所选食品 / 作物 *",
    "input_2_title": "目标保鲜周期",
    "dur_years": "年",
    "dur_months": "月",
    "dur_weeks": "周",
    "dur_days": "天",
    "total_target_storage_duration": "总目标保鲜周期：",
    "input_3_title": "包装照片",
    "click_browse_photo": "点击上传或拍照检测",
    "input_4_title": "起始城市 → 目的城市",
    "lbl_origin_city": "起始地 *",
    "lbl_dest_city": "目的地 *",
    "lbl_transport_mode": "运输方式 *",
    "btn_analyze": "✨ 立即智能分析",
    "ai_analysis_engine": "AI 包装决策引擎",
    "why_this_packaging": "为什么推荐此包装？",
    "recommended_packaging": "推荐包装方案",
    "transport_advice_farmers": "🚛 农户运输与仓储实用建议",
    "technical_pack_spec": "工业级包装工程规格书",
    "opt_history_title": "优化历史记录",
    "btn_clear_history": "🗑️ 清空历史记录"
}

# 12. Arabic (Saudi Arabia)
AR = {
    **BASE_EN,
    "app_name": "PackSense AI",
    "tagline": "تغليف ذكي • طعام صحي • مستقبل مشرق",
    "nav_home": "الرئيسية",
    "nav_workspace": "مساحة العمل",
    "nav_packaudit": "تدقيق العبوة",
    "nav_history": "السجل",
    "nav_about": "حول النظام",
    "language_select": "اللغة",
    "visual_analysis_title": "التحليل المرئي للتغليف",
    "current_packaging": "التغليف الحالي",
    "material_structure": "هيكل المادة",
    "barrier_grade": "درجة الحاجز",
    "shelf_life": "فترة الصلاحية",
    "days": "أيام",
    "ai_recommended": "موصى به بالذكاء الاصطناعي",
    "expected_shelf_life": "العمر المتوقع للمنتج",
    "packaging_unit_eco_score": "التقييم البيئي للعبوة",
    "mode_farmer": "👨‍🌾 وضع المزارع / المشاريع الصغيرة",
    "mode_farmer_subtitle": "إرشادات عملية ومبسطة، فترة الصلاحية والتكلفة",
    "mode_industry": "🔬 وضع الصناعة / المختبر",
    "lbl_selected_food": "السلعة الغذائية المحددة *",
    "btn_analyze": "✨ تحليل ذكي",
    "why_this_packaging": "لماذا تم اختيار هذا التغليف؟",
    "recommended_packaging": "التغليف الموصى به",
    "transport_advice_farmers": "🚛 نصائح النقل والتخزين للمزارعين",
    "btn_clear_history": "🗑️ مسح السجل"
}

# 13. Portuguese (Brazil / Portugal)
PT = {
    **BASE_EN,
    "app_name": "PackSense AI",
    "tagline": "Embalagem Inteligente • Alimentos Saudáveis • Futuro Sustentável",
    "nav_home": "Início",
    "nav_workspace": "Espaço de Trabalho",
    "nav_packaudit": "Auditoria de Embalagem",
    "nav_history": "Histórico",
    "nav_about": "Sobre",
    "language_select": "Idioma",
    "visual_analysis_title": "ANÁLISE VISUAL DA EMBALAGEM",
    "current_packaging": "Embalagem Atual",
    "material_structure": "Estrutura do Material",
    "shelf_life": "Vida Útil",
    "days": "Dias",
    "ai_recommended": "Recomendado por IA",
    "expected_shelf_life": "Vida Útil Esperada",
    "packaging_unit_eco_score": "Pontuação Ecológica",
    "mode_farmer": "👨‍🌾 Modo Produtor / PME",
    "mode_farmer_subtitle": "Diretrizes práticas simples, vida útil e custos",
    "mode_industry": "🔬 Modo Indústria / Laboratório",
    "lbl_selected_food": "Alimento / Produto Selecionado *",
    "btn_analyze": "✨ Analisar",
    "why_this_packaging": "POR QUE ESTA EMBALAGEM?",
    "recommended_packaging": "EMBALAGEM RECOMENDADA",
    "transport_advice_farmers": "🚛 Dicas de Transporte e Armazenamento para Produtores",
    "btn_clear_history": "🗑️ Limpar Histórico"
}

# 14. Russian (Russia)
RU = {
    **BASE_EN,
    "app_name": "PackSense AI",
    "tagline": "Умная упаковка • Здоровая еда • Светлое будущее",
    "nav_home": "Главная",
    "nav_workspace": "Рабочая зона",
    "nav_packaudit": "Аудит упаковки",
    "nav_history": "История",
    "nav_about": "О системе",
    "language_select": "Язык",
    "visual_analysis_title": "ВИЗУАЛЬНЫЙ АНАЛИЗ УПАКОВКИ",
    "current_packaging": "Текущая упаковка",
    "material_structure": "Структура материала",
    "shelf_life": "Срок хранения",
    "days": "Дней",
    "ai_recommended": "Рекомендовано ИИ",
    "expected_shelf_life": "Ожидаемый срок хранения",
    "packaging_unit_eco_score": "Эко-рейтинг упаковки",
    "mode_farmer": "👨‍🌾 Режим Фермера / МСП",
    "mode_farmer_subtitle": "Простые практические рекомендации, сроки и стоимость",
    "mode_industry": "🔬 Режим Промышленности / Лаборатории",
    "lbl_selected_food": "Выбранный продукт *",
    "btn_analyze": "✨ Анализировать",
    "why_this_packaging": "ПОЧЕМУ ЭТА УПАКОВКА?",
    "recommended_packaging": "РЕКОМЕНДОВАННАЯ УПАКОВКА",
    "transport_advice_farmers": "🚛 Советы по перевозке и хранению для фермеров",
    "btn_clear_history": "🗑️ Очистить историю"
}

# 15. Japanese (Japan)
JA = {
    **BASE_EN,
    "app_name": "PackSense AI",
    "tagline": "スマート包装 • より安全な食品 • 明るい未来",
    "nav_home": "ホーム",
    "nav_workspace": "ワークスペース",
    "nav_packaudit": "包装診断",
    "nav_history": "履歴",
    "nav_about": "概要",
    "language_select": "言語",
    "visual_analysis_title": "視覚的パッケージ分析",
    "current_packaging": "現在の包装",
    "material_structure": "材料構造",
    "shelf_life": "賞味・保存期間",
    "days": "日",
    "ai_recommended": "AI推奨包装",
    "expected_shelf_life": "期待される保存期間",
    "packaging_unit_eco_score": "エコスコア",
    "mode_farmer": "👨‍🌾 生産者 / 中小企業モード",
    "mode_farmer_subtitle": "分かりやすい実用的な指針、賞味期限およびコスト",
    "mode_industry": "🔬 産業 / ラボ分析モード",
    "lbl_selected_food": "対象食品・農産物 *",
    "btn_analyze": "✨ 分析を実行",
    "why_this_packaging": "なぜこの包装なのか？",
    "recommended_packaging": "推奨パッケージ",
    "transport_advice_farmers": "🚛 生産者のための輸送および保管アドバイス",
    "btn_clear_history": "🗑️ 履歴を消去"
}

# 16. Italian (Italy)
IT = {
    **BASE_EN,
    "app_name": "PackSense AI",
    "tagline": "Imballaggio Intelligente • Cibo Sano • Futuro Sostenibile",
    "nav_home": "Home",
    "nav_workspace": "Spazio di Lavoro",
    "nav_packaudit": "Audit Imballaggio",
    "nav_history": "Cronologia",
    "nav_about": "Informazioni",
    "language_select": "Lingua",
    "visual_analysis_title": "ANALISI VISIVA DELL'IMBALLAGGIO",
    "current_packaging": "Imballaggio Attuale",
    "material_structure": "Struttura del Materiale",
    "shelf_life": "Durata di Conservazione",
    "days": "Giorni",
    "ai_recommended": "Raccomandato dall'IA",
    "expected_shelf_life": "Durata Prevista",
    "packaging_unit_eco_score": "Punteggio Ecologico",
    "mode_farmer": "👨‍🌾 Modalità Agricoltore / PMI",
    "mode_farmer_subtitle": "Linee guida pratiche semplici, durata e costi",
    "mode_industry": "🔬 Modalità Industria / Laboratorio",
    "lbl_selected_food": "Prodotto Selezionato *",
    "btn_analyze": "✨ Analizza",
    "why_this_packaging": "PERCHÉ QUESTO IMBALLAGGIO?",
    "recommended_packaging": "IMBALLAGGIO RACCOMANDATO",
    "transport_advice_farmers": "🚛 Consigli di Trasporto e Stoccaggio per Agricoltori",
    "btn_clear_history": "🗑️ Cancella Cronologia"
}

# 17. Turkish (Turkey)
TR = {
    **BASE_EN,
    "app_name": "PackSense AI",
    "tagline": "Akıllı Ambalaj • Sağlıklı Gıda • Aydınlık Gelecek",
    "nav_home": "Ana Sayfa",
    "nav_workspace": "Çalışma Alanı",
    "nav_packaudit": "Ambalaj Denetimi",
    "nav_history": "Geçmiş",
    "nav_about": "Hakkında",
    "language_select": "Dil",
    "visual_analysis_title": "GÖRSEL AMBALAJ ANALİZİ",
    "current_packaging": "Mevcut Ambalaj",
    "material_structure": "Malzeme Yapısı",
    "shelf_life": "Raf Ömrü",
    "days": "Gün",
    "ai_recommended": "Yapay Zeka Önerisi",
    "expected_shelf_life": "Beklenen Raf Ömrü",
    "packaging_unit_eco_score": "Eko Puanı",
    "mode_farmer": "👨‍🌾 Çiftçi / KOBİ Modu",
    "mode_farmer_subtitle": "Basit pratik yönergeler, raf ömrü ve maliyetler",
    "mode_industry": "🔬 Sanayi / Laboratuvar Modu",
    "lbl_selected_food": "Seçilen Gıda Ürünü *",
    "btn_analyze": "✨ Analiz Et",
    "why_this_packaging": "NEDEN BU AMBALAJ?",
    "recommended_packaging": "ÖNERİLEN AMBALAJ",
    "transport_advice_farmers": "🚛 Çiftçiler İçin Taşıma ve Depolama Tavsiyeleri",
    "btn_clear_history": "🗑️ Geçmişi Temizle"
}

# 18. Korean (South Korea)
KO = {
    **BASE_EN,
    "app_name": "PackSense AI",
    "tagline": "스마트 패키징 • 건강한 식품 • 지속 가능한 미래",
    "nav_home": "홈",
    "nav_workspace": "워크스페이스",
    "nav_packaudit": "패키징 감사",
    "nav_history": "기록",
    "nav_about": "소개",
    "language_select": "언어",
    "visual_analysis_title": "시각적 패키징 분석",
    "current_packaging": "현재 패키징",
    "material_structure": "소재 구조",
    "shelf_life": "유통기한",
    "days": "일",
    "ai_recommended": "AI 추천 패키징",
    "expected_shelf_life": "예상 보존 기간",
    "packaging_unit_eco_score": "친환경 점수",
    "mode_farmer": "👨‍🌾 농가 / 중소기업 모드",
    "mode_farmer_subtitle": "간단하고 실용적인 가이드라인, 유통기한 및 비용",
    "mode_industry": "🔬 산업 / 실험실 모드",
    "lbl_selected_food": "선택된 농식품 *",
    "btn_analyze": "✨ 분석 시작",
    "why_this_packaging": "이 패키징을 추천하는 이유?",
    "recommended_packaging": "추천 패키징",
    "transport_advice_farmers": "🚛 농가를 위한 운송 및 보관 조언",
    "btn_clear_history": "🗑️ 기록 삭제"
}

# 19. Dutch (Netherlands)
NL = {
    **BASE_EN,
    "app_name": "PackSense AI",
    "tagline": "Slimme Verpakking • Gezonder Voedsel • Duurzame Toekomst",
    "nav_home": "Home",
    "nav_workspace": "Werkplek",
    "nav_packaudit": "PackAudit",
    "nav_history": "Geschiedenis",
    "nav_about": "Over ons",
    "language_select": "Taal",
    "visual_analysis_title": "VISUELE VERPAKKINGSANALYSE",
    "current_packaging": "Huidige Verpakking",
    "material_structure": "Materiaalstructuur",
    "shelf_life": "Houdbaarheid",
    "days": "Dagen",
    "ai_recommended": "AI Aanbevolen",
    "expected_shelf_life": "Verwachte Houdbaarheid",
    "packaging_unit_eco_score": "Duurzaamheidsscore",
    "mode_farmer": "👨‍🌾 Boeren / MKB Modus",
    "mode_farmer_subtitle": "Eenvoudige praktische richtlijnen, houdbaarheid en kosten",
    "mode_industry": "🔬 Industrie / Lab Modus",
    "lbl_selected_food": "Geselecteerd Product *",
    "btn_analyze": "✨ Analyseren",
    "why_this_packaging": "WAAROM DEZE VERPAKKING?",
    "recommended_packaging": "AANBEVOLEN VERPAKKING",
    "transport_advice_farmers": "🚛 Transport- en Bewaaradvies voor Boeren",
    "btn_clear_history": "🗑️ Geschiedenis Wissen"
}

# 20. Vietnamese (Vietnam)
VI = {
    **BASE_EN,
    "app_name": "PackSense AI",
    "tagline": "Bao Bì Thông Minh • Thực Phẩm An Toàn • Tương Lai Bền Vững",
    "nav_home": "Trang Chủ",
    "nav_workspace": "Không Gian Làm Việc",
    "nav_packaudit": "Kiểm Tra Bao Bì",
    "nav_history": "Lịch Sử",
    "nav_about": "Giới Thiệu",
    "language_select": "Ngôn Ngữ",
    "visual_analysis_title": "PHÂN TÍCH BAO BÌ TRỰC QUAN",
    "current_packaging": "Bao Bì Hiện Tại",
    "material_structure": "Cấu Trúc Vật Liệu",
    "shelf_life": "Thời Hạn Sử Dụng",
    "days": "Ngày",
    "ai_recommended": "Được AI Đề Xuất",
    "expected_shelf_life": "Hạn Bảo Quản Dự Kiến",
    "packaging_unit_eco_score": "Điểm Sinh Thái",
    "mode_farmer": "👨‍🌾 Chế Độ Nông Dân / Doanh Nghiệp Nhỏ",
    "mode_farmer_subtitle": "Hướng dẫn thực tế đơn giản, hạn sử dụng và chi phí",
    "mode_industry": "🔬 Chế Độ Công Nghiệp / Phòng Thí Nghiệm",
    "lbl_selected_food": "Nông Sản / Thực Phẩm Đã Chọn *",
    "btn_analyze": "✨ Phân Tích Ngay",
    "why_this_packaging": "TẠI SAO CHỌN BAO BÌ NÀY?",
    "recommended_packaging": "BAO BÌ ĐỀ XUẤT",
    "transport_advice_farmers": "🚛 Lời Khuyên Vận Chuyển & Bảo Quản Cho Nông Dân",
    "btn_clear_history": "🗑️ Xóa Lịch Sử"
}

# 21. Indonesian (Indonesia)
ID = {
    **BASE_EN,
    "app_name": "PackSense AI",
    "tagline": "Kemasan Cerdas • Pangan Sehat • Masa Depan Cerah",
    "nav_home": "Beranda",
    "nav_workspace": "Ruang Kerja",
    "nav_packaudit": "Audit Kemasan",
    "nav_history": "Riwayat",
    "nav_about": "Tentang",
    "language_select": "Bahasa",
    "visual_analysis_title": "ANALISIS KEMASAN VISUAL",
    "current_packaging": "Kemasan Saat Ini",
    "material_structure": "Struktur Bahan",
    "shelf_life": "Masa Simpan",
    "days": "Hari",
    "ai_recommended": "Rekomendasi AI",
    "expected_shelf_life": "Perkiraan Masa Simpan",
    "packaging_unit_eco_score": "Skor Ramah Lingkungan",
    "mode_farmer": "👨‍🌾 Mode Petani / UMKM",
    "mode_farmer_subtitle": "Panduan praktis sederhana, umur simpan dan rincian biaya",
    "mode_industry": "🔬 Mode Industri / Laboratorium",
    "lbl_selected_food": "Komoditas Makanan Terpilih *",
    "btn_analyze": "✨ Analisis",
    "why_this_packaging": "MENGAPA KEMASAN INI?",
    "recommended_packaging": "KEMASAN DIREKOMENDASIKAN",
    "transport_advice_farmers": "🚛 Saran Transportasi & Penyimpanan untuk Petani",
    "btn_clear_history": "🗑️ Hapus Riwayat"
}

# Master translations dictionary for all 21 country languages
TRANSLATIONS = {
    "en": BASE_EN,
    "hi": HI,
    "mr": MR,
    "gu": GU,
    "bn": BN,
    "te": TE,
    "ta": TA,
    "es": ES,
    "fr": FR,
    "de": DE,
    "zh": ZH,
    "ar": AR,
    "pt": PT,
    "ru": RU,
    "ja": JA,
    "it": IT,
    "tr": TR,
    "ko": KO,
    "nl": NL,
    "vi": VI,
    "id": ID
}

# --- AUTO-MERGED KEYS FOR 21 LANGUAGES ---
EXTRA_LOCALIZED_KEYS = {'origin_city': {'en': 'Origin City', 'hi': 'प्रस्थान शहर', 'mr': 'मूळ शहर', 'gu': 'મૂળ શહેર', 'bn': 'উৎপত্তি শহর', 'te': 'ప్రారంభ నగరం', 'ta': 'புறப்படும் நகரம்', 'es': 'Ciudad de origen', 'fr': "Ville d'origine", 'de': 'Abfahrtsort', 'zh': '始发城市', 'ar': 'مدينة المنشأ', 'pt': 'Cidade de origem', 'ru': 'Город отправления', 'ja': '出発都市', 'it': 'Città di origine', 'tr': 'Kalkış Şehri', 'ko': '출발 도시', 'nl': 'Herkomststad', 'vi': 'Thành phố xuất phát', 'id': 'Kota Asal'}, 'destination_city': {'en': 'Destination City', 'hi': 'गंतव्य शहर', 'mr': 'गंतव्य शहर', 'gu': 'ગંતવ્ય શહેર', 'bn': 'গন্তব্য শহর', 'te': 'చేరుకునే నగరం', 'ta': 'சேருமிடம் நகரம்', 'es': 'Ciudad de destino', 'fr': 'Ville de destination', 'de': 'Zielort', 'zh': '目的地城市', 'ar': 'مدينة الوجهة', 'pt': 'Cidade de destino', 'ru': 'Город назначения', 'ja': '目的都市', 'it': 'Città di destinazione', 'tr': 'Varış Şehri', 'ko': '도착 도시', 'nl': 'Bestemmingsstad', 'vi': 'Thành phố đích', 'id': 'Kota Tujuan'}, 'history_title': {'en': 'Optimization History', 'hi': 'अनुकूलन इतिहास', 'mr': 'ऑप्टिमायझेशन इतिहास', 'gu': 'ઓપ્ટિમાઇઝેશન ઇતિહાસ', 'bn': 'অপ্টিমাইজেশন ইতিহাস', 'te': 'ఆప్టిమైజేషన్ చరిత్ర', 'ta': 'மேம்படுத்தல் வரலாறு', 'es': 'Historial de optimización', 'fr': "Historique d'optimisation", 'de': 'Optimierungsverlauf', 'zh': '优化历史记录', 'ar': 'سجل التحسين', 'pt': 'Histórico de otimização', 'ru': 'История оптимизации', 'ja': '最適化履歴', 'it': 'Cronologia ottimizzazioni', 'tr': 'Optimizasyon Geçmişi', 'ko': '최적화 내역', 'nl': 'Optimalisatiegeschiedenis', 'vi': 'Lịch sử tối ưu hóa', 'id': 'Riwayat Optimasi'}, 'no_history_records': {'en': 'No local optimization history saved yet. Run an analysis above to save your first record.', 'hi': 'अभी तक कोई स्थानीय अनुकूलन इतिहास सहेजा नहीं गया है। अपना पहला रिकॉर्ड सहेजने के लिए ऊपर एक विश्लेषण चलाएं।', 'mr': 'अद्याप कोणताही स्थानिक ऑप्टिमायझेशन इतिहास जतन केलेला नाही. आपला पहिला रेकॉर्ड जतन करण्यासाठी वर विश्लेषण चालवा.', 'gu': 'હજુ સુધી કોઈ સ્થાનિક ઓપ્ટિમાઇઝેશન ઇતિહાસ સાચવવામાં આવ્યો નથી. તમારો પ્રથમ રેકોર્ડ સાચવવા માટે ઉપર વિશ્લેષણ ચલાવો.', 'bn': 'এখনও কোনো স্থানীয় অপ্টিমাইজেশন ইতিহাস সংরক্ষিত হয়নি। আপনার প্রথম রেকর্ড সংরক্ষণ করতে উপরে একটি বিশ্লেষণ চালান।', 'te': 'ఇంకా స్థానిక ఆప్టిమైజేషన్ చరిత్ర ఏదీ సేవ్ కాలేదు. మీ మొదటి రికార్డును సేవ్ చేయడానికి పైన విశ్లేషణను అమలు చేయండి.', 'ta': 'இன்னும் உள்ளூர் மேம்படுத்தல் வரலாறு எதுவும் சேமிக்கப்படவில்லை. உங்கள் முதல் பதிவைச் சேமிக்க மேலே ஒரு பகுப்பாய்வை இயக்கவும்.', 'es': 'Aún no hay historial de optimización local guardado. Ejecute un análisis arriba para guardar su primer registro.', 'fr': "Aucun historique d'optimisation enregistré pour l'instant. Lancez une analyse ci-dessus pour enregistrer votre premier enregistrement.", 'de': 'Noch kein lokaler Optimierungsverlauf gespeichert. Führen Sie oben eine Analyse durch, um Ihren ersten Datensatz zu speichern.', 'zh': '尚未保存本地优化历史记录。在上方运行分析以保存您的第一条记录。', 'ar': 'لم يتم حفظ سجل تحسين محلي بعد. قم بتشغيل تحليل أعلاه لحفظ سجلك الأول.', 'pt': 'Nenhum histórico de otimização local salvo ainda. Execute uma análise acima para salvar seu primeiro registro.', 'ru': 'Локальная история оптимизации пока не сохранена. Запустите анализ выше, чтобы сохранить первую запись.', 'ja': 'ローカルの最適化履歴はまだ保存されていません。上記で分析を実行して最初のレコードを保存してください。', 'it': "Nessuna cronologia salvata. Esegui un'analisi sopra per salvare il primo record.", 'tr': 'Henüz kayıtlı optimizasyon geçmişi yok. İlk kaydınızı oluşturmak için yukarıdan analiz yapın.', 'ko': '저장된 로컬 최적화 내역이 없습니다. 위에서 분석을 실행하여 첫 번째 기록을 저장하세요.', 'nl': 'Nog geen optimalisatiegeschiedenis opgeslagen. Voer hierboven een analyse uit om uw eerste record op te slaan.', 'vi': 'Chưa có lịch sử tối ưu hóa cục bộ. Chạy phân tích ở trên để lưu bản ghi đầu tiên.', 'id': 'Belum ada riwayat optimasi lokal yang tersimpan. Jalankan analisis di atas untuk menyimpan rekaman pertama Anda.'}, 'mode': {'en': 'Mode', 'hi': 'मोड', 'mr': 'मोड', 'gu': 'મોડ', 'bn': 'মোড', 'te': 'మోడ్', 'ta': 'பயன்முறை', 'es': 'Modo', 'fr': 'Mode', 'de': 'Modus', 'zh': '模式', 'ar': 'الوضع', 'pt': 'Modo', 'ru': 'Режим', 'ja': 'モード', 'it': 'Modalità', 'tr': 'Mod', 'ko': '모드', 'nl': 'Modus', 'vi': 'Chế độ', 'id': 'Mode'}, 'role': {'en': 'Role', 'hi': 'भूमिका', 'mr': 'भूमिका', 'gu': 'ભૂમિકા', 'bn': 'ভূমিকা', 'te': 'పాత్ర', 'ta': 'பங்கு', 'es': 'Rol', 'fr': 'Rôle', 'de': 'Rolle', 'zh': '角色', 'ar': 'الدور', 'pt': 'Função', 'ru': 'Роль', 'ja': '役割', 'it': 'Ruolo', 'tr': 'Rol', 'ko': '역할', 'nl': 'Rol', 'vi': 'Vai trò', 'id': 'Peran'}, 'next': {'en': 'Next', 'hi': 'अगला', 'mr': 'पुढील', 'gu': 'આગળ', 'bn': 'পরবর্তী', 'te': 'తదుపరి', 'ta': 'அடுத்து', 'es': 'Siguiente', 'fr': 'Suivant', 'de': 'Weiter', 'zh': '下一步', 'ar': 'التالي', 'pt': 'Próximo', 'ru': 'Далее', 'ja': '次へ', 'it': 'Avanti', 'tr': 'İleri', 'ko': '다음', 'nl': 'Volgende', 'vi': 'Tiếp theo', 'id': 'Berikutnya'}, 'academic_disclaimer': {'en': 'PackSense AI Packaging Decision Support System. Developed for Post-Harvest Agricultural Engineering & Industrial Packaging Research.', 'hi': 'पैकसेंस एआई पैकेजिंग निर्णय समर्थन प्रणाली। फसल कटाई उपरांत कृषि इंजीनियरिंग और औद्योगिक पैकेजिंग अनुसंधान के लिए विकसित।', 'mr': 'पॅकसेन्स एआय पॅकेजिंग निर्णय समर्थन प्रणाली. काढणीनंतरच्या कृषी अभियांत्रिकी आणि औद्योगिक पॅकेजिंग संशोधनासाठी विकसित.', 'gu': 'પેકસિન્સ AI પેકેજિંગ નિર્ણય સપોર્ટ સિસ્ટમ. લણણી પછીના કૃષિ એન્જિનિયરિંગ અને ઔદ્યોગિક પેકેજિંગ સંશોધન માટે વિકસિત.', 'bn': 'প্যাকসেন্স এআই প্যাকেজিং ডিসিশন সাপোর্ট সিস্টেম। ফসল তোলার পরবর্তী কৃষি প্রকৌশল ও শিল্প প্যাকেজিং গবেষণার জন্য তৈরি।', 'te': 'ప్యాక్\u200cసెన్స్ AI ప్యాకేజింగ్ నిర్ణయ సహాయ వ్యవస్థ. పోస్ట్-హార్వెస్ట్ అగ్రికల్చరల్ ఇంజనీరింగ్ & ఇండస్ట్రియల్ ప్యాకేజింగ్ రీసెర్చ్ కోసం అభివృద్ధి చేయబడింది.', 'ta': 'பேக்சென்ஸ் AI பேக்கேஜிங் முடிவு ஆதரவு அமைப்பு. அறுவடைக்குப் பிந்தைய வேளாண்மை பொறியியல் மற்றும் தொழில்துறை பேக்கேஜிங் ஆராய்ச்சிக்காக உருவாக்கப்பட்டது.', 'es': 'Sistema de soporte de decisiones de empaque PackSense AI. Desarrollado para investigación de ingeniería agrícola poscosecha y empaque industrial.', 'fr': "Système d'aide à la décision d'emballage PackSense AI. Développé pour l'ingénierie agricole post-récolte et la recherche sur l'emballage industriel.", 'de': 'PackSense AI Verpackungs-Entscheidungsunterstützungssystem. Entwickelt für Nachernte-Agrartechnik & industrielle Verpackungsforschung.', 'zh': 'PackSense AI 包装决策支持系统。专为收获后农业工程与工业包装研究开发。', 'ar': 'نظام دعم قرار التعبئة والتغليف بالذكاء الاصطناعي PackSense. تم تطويره لأبحاث الهندسة الزراعية بعد الحصاد والتعبئة والتغليف الصناعي.', 'pt': 'Sistema de suporte à decisão de embalagens PackSense AI. Desenvolvido para engenharia agrícola pós-colheita e pesquisa de embalagens industriais.', 'ru': 'Система поддержки решений по упаковке PackSense AI. Разработана для послеуборочной сельскохозяйственной инженерии и промышленных исследований.', 'ja': 'PackSense AI 包装意思決定支援システム。収穫後農業工学および産業用包装研究向けに開発。', 'it': "Sistema di supporto alle decisioni di imballaggio PackSense AI. Sviluppato per ingegneria agricola post-raccolta e ricerca sull'imballaggio industriale.", 'tr': 'PackSense AI Ambalaj Karar Destek Sistemi. Hasat Sonrası Tarım Mühendisliği ve Endüstriyel Ambalaj Araştırmaları için geliştirilmiştir.', 'ko': 'PackSense AI 포장 의사 결정 지원 시스템. 수확 후 농업 공학 및 산업 포장 연구를 위해 개발되었습니다.', 'nl': 'PackSense AI Verpakkingsbeslissingsondersteuningssysteem. Ontwikkeld voor post-oogst landbouwtechniek en industrieel verpakkingsonderzoek.', 'vi': 'Hệ thống hỗ trợ quyết định đóng gói PackSense AI. Được phát triển cho kỹ thuật nông nghiệp sau thu hoạch và nghiên cứu đóng gói công nghiệp.', 'id': 'Sistem Pendukung Keputusan Pengemasan PackSense AI. Dikembangkan untuk teknik pertanian pascapanen & penelitian pengemasan industri.'}, 'btn_upload_image': {'en': 'Upload Package Image', 'hi': 'पैकेज छवि अपलोड करें', 'mr': 'पॅकेज प्रतिमा अपलोड करा', 'gu': 'પેકેજ ઇમેજ અપલોડ કરો', 'bn': 'প্যাকেজ ছবি আপলোড করুন', 'te': 'ప్యాకేజ్ చిత్రాన్ని అప్\u200cలోడ్ చేయండి', 'ta': 'தொகுப்பு படத்தை பதிவேற்றவும்', 'es': 'Subir imagen del paquete', 'fr': "Télécharger l'image de l'emballage", 'de': 'Verpackungsbild hochladen', 'zh': '上传包装图片', 'ar': 'تحميل صورة العبوة', 'pt': 'Carregar imagem da embalagem', 'ru': 'Загрузить изображение упаковки', 'ja': 'パッケージ画像をアップロード', 'it': 'Carica immagine confezione', 'tr': 'Paket Görseli Yükle', 'ko': '포장 이미지 업로드', 'nl': 'Verpakkingsafbeelding uploaden', 'vi': 'Tải lên hình ảnh bao bì', 'id': 'Unggah Gambar Kemasan'}, 'lbl_channel_b_desc': {'en': 'Select standard camera image (JPG/PNG)', 'hi': 'मानक कैमरा छवि (JPG/PNG) चुनें', 'mr': 'मानक कॅमेरा प्रतिमा (JPG/PNG) निवडा', 'gu': 'પ્રમાણભૂત કૅમેરા છબી (JPG/PNG) પસંદ કરો', 'bn': 'সাধারণ ক্যামেরা ছবি (JPG/PNG) নির্বাচন করুন', 'te': 'ప్రామాణిక కెమెరా చిత్రం (JPG/PNG) ఎంచుకోండి', 'ta': 'நிலையான கேமரா படத்தை (JPG/PNG) தேர்ந்தெடுக்கவும்', 'es': 'Seleccionar imagen de cámara estándar (JPG/PNG)', 'fr': "Sélectionnez une image d'appareil photo standard (JPG/PNG)", 'de': 'Standard-Kamerabild (JPG/PNG) auswählen', 'zh': '选择标准相机图像 (JPG/PNG)', 'ar': 'حدد صورة الكاميرا القياسية (JPG/PNG)', 'pt': 'Selecione uma imagem de câmera padrão (JPG/PNG)', 'ru': 'Выберите стандартное фото камеры (JPG/PNG)', 'ja': '標準カメラ画像 (JPG/PNG) を選択', 'it': 'Seleziona immagine fotocamera standard (JPG/PNG)', 'tr': 'Standart kamera görüntüsü seçin (JPG/PNG)', 'ko': '표준 카메라 이미지(JPG/PNG) 선택', 'nl': 'Selecteer standaard camerabeeld (JPG/PNG)', 'vi': 'Chọn hình ảnh máy ảnh tiêu chuẩn (JPG/PNG)', 'id': 'Pilih gambar kamera standar (JPG/PNG)'}, 'hero_title': {'en': 'Next-Gen AI Packaging Intelligence for Perishables & Food Supply Chains', 'hi': 'खाद्य आपूर्ति श्रृंखला के लिए अगली पीढ़ी की एआई पैकेजिंग बुद्धिमत्ता', 'mr': 'अन्न पुरवठा साखळीसाठी नेक्स्ट-जनरेशन एआय पॅकेजिंग बुद्धिमत्ता', 'gu': 'ખાદ્ય પુરવઠા સાંકળ માટે નેક્સ્ટ-જનરેશન AI પેકેજિંગ બુદ્ધિ', 'bn': 'খাদ্য সরবরাহ শৃঙ্খলের জন্য পরবর্তী প্রজন্মের এআই প্যাকেজিং বুদ্ধিমত্তা', 'te': 'ఆహార సరఫరా గొలుసు కోసం తరువాతి తరం AI ప్యాకేజింగ్ మేధస్సు', 'ta': 'உணவு விநியோகச் சங்கிலிக்கான அடுத்த தலைமுறை AI பேக்கேஜிங் நுண்ணறிவு', 'es': 'Inteligencia de empaque con IA de próxima generación para cadenas de suministro perecederas', 'fr': "Intelligence d'emballage IA de nouvelle génération pour les chaînes d'approvisionnement périssables", 'de': 'KI-Verpackungsintelligenz der nächsten Generation für verderbliche Lebensmittel-Lieferketten', 'zh': '面向易腐食品供应链的下一代 AI 包装智能平台', 'ar': 'ذكاء التعبئة والتغليف بالذكاء الاصطناعي من الجيل التالي لسلاسل إمداد الأغذية سريعة التلف', 'pt': 'Inteligência de embalagem com IA de última geração para cadeias de suprimentos de perecíveis', 'ru': 'Интеллектуальная система упаковки нового поколения на базе ИИ для цепочек поставок продуктов питания', 'ja': '生鮮食品サプライチェーン向け次世代AI包装インテリジェンス', 'it': 'Intelligenza di imballaggio AI di nuova generazione per le catene di fornitura alimentari', 'tr': 'Bozulabilir Gıda Tedarik Zincirleri için Yeni Nesil Yapay Zeka Ambalaj Zekası', 'ko': '부패하기 쉬운 식품 공급망을 위한 차세대 AI 포장 지능', 'nl': 'Next-Gen AI Verpakkingsintelligentie voor bederfelijke voedseltoeleveringsketens', 'vi': 'Trí tuệ đóng gói AI thế hệ mới cho chuỗi cung ứng thực phẩm dễ hỏng', 'id': 'Intelijen Pengemasan AI Generasi Berikutnya untuk Rantai Pasok Makanan Segar'}, 'hero_subtitle': {'en': 'Prevent post-harvest loss, optimize ASTM barrier properties, cut plastic consumption, and guarantee freshness across multi-climate transit corridors.', 'hi': 'फसल के नुकसान को रोकें, बाधा गुणों को अनुकूलित करें, प्लास्टिक की खपत कम करें और ताजगी की गारंटी दें।', 'mr': 'काढणीनंतरचे नुकसान रोखा, अडथळा गुणधर्म ऑप्टिमाइझ करा, प्लास्टिक वापर कमी करा आणि ताजेपणाची हमी द्या.', 'gu': 'લણણી પછીના નુકસાનને અટકાવો, અવરોધ ગુણધર્મોને ઓપ્ટિમાઇઝ કરો, પ્લાસ્ટિક વપરાશ ઘટાડો અને તાજગીની ખાતરી આપો.', 'bn': 'ফসল কাটার পরবর্তী অপচয় রোধ করুন, বাধা বৈশিষ্ট্য অপ্টিমাইজ করুন, প্লাস্টিক ব্যবহার হ্রাস করুন এবং সতেজতা নিশ্চিত করুন।', 'te': 'పంట నష్టాన్ని నివారించండి, అవరోధ లక్షణాలను ఆప్టిమైజ్ చేయండి, ప్లాస్టిక్ వినియోగాన్ని తగ్గించండి మరియు తాజాదనాన్ని హామీ ఇవ్వండి.', 'ta': 'அறுவடைக்குப் பிந்தைய இழப்பைத் தடுக்கவும், தடை பண்புகளை மேம்படுத்தவும், பிளாஸ்டிக் நுகர்வைக் குறைக்கவும், புத்துணர்ச்சியை உறுதி செய்யவும்.', 'es': 'Evite las pérdidas poscosecha, optimice las propiedades de barrera, reduzca el plástico y garantice la frescura.', 'fr': 'Prévenez les pertes post-récolte, optimisez les propriétés barrières, réduisez le plastique et garantissez la fraîcheur.', 'de': 'Ernteverluste verhindern, Barriereeigenschaften optimieren, Plastikverbrauch senken und Frische garantieren.', 'zh': '减少采后损耗，优化 ASTM 阻隔性能，削减塑料消耗，并在多气候运输路线中保障新鲜度。', 'ar': 'منع خسائر ما بعد الحصاد، وتحسين خصائص الحاجز، وتقليل استهلاك البلاستيك، وضمان النضارة.', 'pt': 'Evite perdas pós-colheita, otimize as propriedades de barreira, reduza o plástico e garanta o frescor.', 'ru': 'Предотвращайте потери после сбора урожая, оптимизируйте барьерные свойства, сокращайте пластик и гарантируйте свежесть.', 'ja': '収穫後の廃棄を防止し、バリア特性を最適化し、プラスチック使用量を削減し、鮮度を保証します。', 'it': 'Previeni le perdite post-raccolta, ottimizza le proprietà barriera, riduci la plastica e garantisci la freschezza.', 'tr': 'Hasat sonrası kayıpları önleyin, bariyer özelliklerini optimize edin, plastik kullanımını azaltın ve tazeliği garanti edin.', 'ko': '수확 후 손실을 방지하고 배리어 특성을 최적화하며 플라스틱 소비를 줄이고 신선도를 보장합니다.', 'nl': 'Voorkom verliezen na de oogst, optimaliseer barrière-eigenschappen, verminder plasticgebruik en garandeer versheid.', 'vi': 'Ngăn ngừa thất thoát sau thu hoạch, tối ưu hóa đặc tính rào cản, giảm tiêu thụ nhựa và đảm bảo độ tươi ngon.', 'id': 'Cegah kerugian pascapanen, optimalkan sifat pelindung, kurangi konsumsi plastik, dan jamin kesegaran.'}, 'feat_recommendation_title': {'en': 'Intelligent Bio-Barrier Matching', 'hi': 'बुद्धिमान जैव-बाधा मिलान', 'mr': 'इंटेलिजंट बायो-बॅरियर मॅचिंग', 'gu': 'બુદ્ધિશાળી બાયો-બેરિયર મેચિંગ', 'bn': 'বুদ্ধিমান বায়ো-ব্যারিয়ার ম্যাচিং', 'te': 'ఇంటెలిజెంట్ బయో-బారియర్ మ్యాచింగ్', 'ta': 'புத்திசாலித்தனமான பயோ-பேரியர் பொருத்தம்', 'es': 'Coincidencia inteligente de biobarrera', 'fr': 'Correspondance intelligente de bio-barrière', 'de': 'Intelligenter Bio-Barriere-Abgleich', 'zh': '智能生物阻隔匹配', 'ar': 'مطابقة الحاجز الحيوي الذكية', 'pt': 'Combinação inteligente de biobarreira', 'ru': 'Интеллектуальный подбор биобарьера', 'ja': 'インテリジェント・バイオバリアマッチング', 'it': 'Abbinamento intelligente bio-barriera', 'tr': 'Akıllı Biyo-Bariyer Eşleştirme', 'ko': '지능형 바이오 배리어 매칭', 'nl': 'Intelligente bio-barrière matching', 'vi': 'Khớp rào cản sinh học thông minh', 'id': 'Pencocokan Bio-Barrier Cerdas'}, 'feat_recommendation_desc': {'en': 'Calculates calibrated Oxygen (OTR) and Moisture (WVTR) barrier requirements dynamically based on commodity respiration rates.', 'hi': 'श्वसन दर के आधार पर ऑक्सीजन (OTR) और नमी (WVTR) आवश्यकताओं की गणना करता है।', 'mr': 'श्वसन दरावर आधारित ऑक्सिजन (OTR) आणि आर्द्रता (WVTR) आवश्यकतांची गणना करते.', 'gu': 'શ્વસન દરના આધારે ઓક્સિજન (OTR) અને ભેજ (WVTR) જરૂરિયાતોની ગણતરી કરે છે.', 'bn': 'শ্বসন হারের উপর ভিত্তি করে অক্সিজেন (OTR) এবং আর্দ্রতা (WVTR) প্রয়োজনীয়তা গণনা করে।', 'te': 'శ్వాసక్రియ రేటు ఆధారంగా ఆక్సిజన్ (OTR) మరియు తేమ (WVTR) అవసరాలను లెక్కిస్తుంది.', 'ta': 'சுவாச விகிதத்தின் அடிப்படையில் ஆக்ஸிஜன் (OTR) மற்றும் ஈரப்பதம் (WVTR) தேவைகளைக் கணக்கிடுகிறது.', 'es': 'Calcula los requisitos de barrera de oxígeno (OTR) y humedad (WVTR) en función de las tasas de respiración.', 'fr': "Calcule les exigences de barrière à l'oxygène (OTR) et à l'humidité (WVTR) en fonction des taux de respiration.", 'de': 'Berechnet Sauerstoff- (OTR) und Feuchtigkeitsbarriereanforderungen (WVTR) basierend auf Atmungsraten.', 'zh': '根据商品呼吸速率动态计算校准的氧气 (OTR) 和水蒸气 (WVTR) 阻隔需求。', 'ar': 'يحسب متطلبات حاجز الأكسجين والرطوبة بناءً على معدلات التنفس.', 'pt': 'Calcula os requisitos de barreira de oxigênio (OTR) e umidade (WVTR) com base nas taxas de respiração.', 'ru': 'Рассчитывает требования к кислородному (OTR) и влагозащитному (WVTR) барьеру на основе скорости дыхания.', 'ja': '青果物の呼吸速度に基づいて酸素 (OTR) および水分 (WVTR) バリア要件を動的に計算します。', 'it': "Calcola i requisiti di barriera all'ossigeno (OTR) e all'umidità (WVTR) in base ai tassi di respirazione.", 'tr': 'Solunum oranlarına göre kalibre edilmiş Oksijen (OTR) ve Nem (WVTR) bariyer gereksinimlerini hesaplar.', 'ko': '호흡률을 기반으로 보정된 산소(OTR) 및 수분(WVTR) 차단 요구 사항을 계산합니다.', 'nl': 'Berekent zuurstof- (OTR) en vochtbarrière-eisen (WVTR) op basis van ademhalingssnelheden.', 'vi': 'Tính toán các yêu cầu rào cản oxy (OTR) và độ ẩm (WVTR) dựa trên tốc độ hô hấp.', 'id': 'Menghitung kebutuhan pelindung Oksigen (OTR) dan Kelembapan (WVTR) berdasarkan laju respirasi.'}, 'feat_climate_title': {'en': 'Multi-City Climate Stress Mapping', 'hi': 'बहु-शहर जलवायु तनाव मानचित्रण', 'mr': 'मल्टी-सिटी हवामान ताण मॅपिंग', 'gu': 'બહુ-શહેર આબોહવા તણાવ મેપિંગ', 'bn': 'মাল্টি-সিটি জলবায়ু চাপ ম্যাপিং', 'te': 'మల్టీ-సిటీ వాతావరణ ఒత్తిడి మ్యాపింగ్', 'ta': 'பல நகர காலநிலை அழுத்த வரைபடமாக்கல்', 'es': 'Mapeo de estrés climático multiciudad', 'fr': 'Cartographie du stress climatique multi-villes', 'de': 'Multi-City-Klimabelastungskartierung', 'zh': '多城市气候压力测绘', 'ar': 'تخطيط الإجهاد المناخي متعدد المدن', 'pt': 'Mapeamento de estresse climático multicidades', 'ru': 'Картирование климатического стресса для разных городов', 'ja': 'マルチ都市気候ストレスマッピング', 'it': 'Mappatura dello stress climatico multi-città', 'tr': 'Çok Şehirli İklim Stresi Haritalaması', 'ko': '다중 도시 기후 스트레스 매핑', 'nl': 'Multi-stad klimaatstresskartering', 'vi': 'Bản đồ căng thẳng khí hậu đa thành phố', 'id': 'Pemetaan Stres Iklim Multi-Kota'}, 'feat_climate_desc': {'en': 'Models actual ambient temperature and humidity shifts across all Indian transit corridors.', 'hi': 'सभी भारतीय पारगमन गलियारों में वास्तविक परिवेश तापमान और आर्द्रता परिवर्तन का मॉडल बनाता है।', 'mr': 'सर्व भारतीय वाहतूक कॉरिडॉरमधील वास्तविक तापमान आणि आर्द्रता बदलांचे मॉडेल तयार करते.', 'gu': 'તમામ ભારતીય પરિવહન કોરિડોરમાં વાસ્તવિક તાપમાન અને ભેજના ફેરફારોનું મોડેલ બનાવે છે.', 'bn': 'সমস্ত ভারতীয় ট্রানজিট করিডোর জুড়ে বাস্তব পরিবেষ্টিত তাপমাত্রা এবং আর্দ্রতার পরিবর্তনের মডেল করে।', 'te': 'అన్ని భారతీయ రవాణా కారిడార్లలో వాస్తవ ఉష్ణోగ్రత మరియు తేమ మార్పులను మోడల్ చేస్తుంది.', 'ta': 'அனைத்து இந்திய போக்குவரத்து வழித்தடங்களிலும் உண்மையான வெப்பநிலை மற்றும் ஈரப்பத மாற்றங்களை மாதிரியாக்குகிறது.', 'es': 'Modela los cambios reales de temperatura ambiente y humedad en todos los corredores de tránsito de la India.', 'fr': "Modélise les variations réelles de température et d'humidité sur tous les corridors de transit indiens.", 'de': 'Modelliert tatsächliche Umgebungstemperatur- und Feuchtigkeitsverschiebungen auf indischen Transitkorridoren.', 'zh': '模拟所有运输走廊中的实际环境温度和湿度变化。', 'ar': 'محاكاة التغيرات الفعلية في درجة الحرارة المحيطة والرطوبة عبر جميع ممرات العبور.', 'pt': 'Modela as mudanças reais de temperatura e umidade ambiente em todos os corredores de trânsito.', 'ru': 'Моделирует реальные колебания температуры и влажности на всех транзитных коридорах.', 'ja': 'すべての輸送ルートにおける実際の周囲温度と湿度の変化をモデル化します。', 'it': 'Modella le variazioni effettive di temperatura e umidità ambientale attraverso tutti i corridoi di transito.', 'tr': 'Tüm transit koridorlarındaki gerçek ortam sıcaklığı ve nem değişimlerini modeller.', 'ko': '모든 운송 경로의 실제 주변 온도 및 습도 변화를 모델링합니다.', 'nl': 'Modelleert werkelijke temperatuur- en vochtigheidsverschuivingen in transitcorridors.', 'vi': 'Mô hình hóa sự thay đổi nhiệt độ và độ ẩm môi trường thực tế trên tất cả các hành lang vận chuyển.', 'id': 'Memodelkan perubahan suhu dan kelembapan sekitar yang sebenarnya di semua koridor transit.'}, 'feat_green_title': {'en': 'Sustainability & Eco-Impact', 'hi': 'स्थिरता और पर्यावरण प्रभाव', 'mr': 'शाश्वतता आणि पर्यावरणीय प्रभाव', 'gu': 'ટકાઉપણું અને પર્યાવરણીય પ્રભાવ', 'bn': 'স্থায়িত্ব এবং পরিবেশগত প্রভাব', 'te': 'స్థిరత్వం మరియు పర్యావరణ ప్రభావం', 'ta': 'நிலைத்தன்மை & சுற்றுச்சூழல் தாக்கம்', 'es': 'Sostenibilidad e impacto ecológico', 'fr': 'Durabilité et impact écologique', 'de': 'Nachhaltigkeit & Öko-Auswirkungen', 'zh': '可持续性与生态影响', 'ar': 'الاستدامة والأثر البيئي', 'pt': 'Sustentabilidade e impacto ecológico', 'ru': 'Устойчивое развитие и экологическое воздействие', 'ja': '持続可能性と環境への影響', 'it': 'Sostenibilità e impatto ecologico', 'tr': 'Sürdürülebilirlik ve Ekolojik Etki', 'ko': '지속 가능성 및 친환경 영향', 'nl': 'Duurzaamheid & milieu-impact', 'vi': 'Tính bền vững & tác động sinh thái', 'id': 'Keberlanjutan & Dampak Ekologis'}, 'feat_green_desc': {'en': 'Recommends down-gauged films, certified biopolymers, and circular recyclability metrics to lower carbon footprints.', 'hi': 'कार्बन पदचिह्न को कम करने के लिए डाउन-गेज फिल्मों, प्रमाणित बायो-पॉलिमर और रीसाइक्लिंग मेट्रिक्स की सिफारिश करता है।', 'mr': 'कार्बन फूटप्रिंट कमी करण्यासाठी डाऊन-गेज्ड फिल्म्स, प्रमाणित बायो-पॉलिमर आणि पुनर्वापर मेट्रिक्सची शिफारस करते.', 'gu': 'કાર્બન ફૂટપ્રિન્ટ ઘટાડવા માટે ડાઉન-ગેજ્ડ ફિલ્મો, પ્રમાણિત બાયો-પોલિમર અને રિસાયક્લિંગ મેટ્રિક્સની ભલામણ કરે છે.', 'bn': 'কার্বন পদচিহ্ন কমাতে ডাউন-গেজ ফিল্ম, প্রত্যয়িত বায়োপলিমার এবং বৃত্তাকার পুনর্ব্যবহারযোগ্য মেট্রিক্সের সুপারিশ করে।', 'te': 'కార్బన్ పాదముద్రను తగ్గించడానికి డౌన్-గేజ్ ఫిల్మ్\u200cలు, ధృవీకరించబడిన బయో-పాలిమర్\u200cలను సిఫార్సు చేస్తుంది.', 'ta': 'கார்பன் தடயத்தைக் குறைக்க மெலிதான படங்கள், சான்றளிக்கப்பட்ட பயோபாலிமர்கள் மற்றும் மறுசுழற்சி அளவீடுகளை பரிந்துரைக்கிறது.', 'es': 'Recomienda películas de menor calibre, biopolímeros certificados y métricas de reciclabilidad para reducir la huella de carbono.', 'fr': 'Recommande des films amincis, des biopolymères certifiés et des mesures de recyclabilité circulaire.', 'de': 'Empfiehlt dünnere Folien, zertifizierte Biopolymere und Recycling-Metriken zur Reduzierung des CO2-Fußabdrucks.', 'zh': '推荐减薄膜、经过认证的生物聚合物和循环可回收性指标，以降低碳足迹。', 'ar': 'يوصي بأفلام رقيقة وبوليمرات حيوية معتمدة ومقاييس إعادة التدوير لتقليل البصمة الكربونية.', 'pt': 'Recomenda filmes de menor espessura, biopolímeros certificados e métricas de reciclabilidade circular.', 'ru': 'Рекомендует пленки уменьшенной толщины, сертифицированные биополимеры и показатели переработки.', 'ja': '薄肉化フィルム、認証バイオポリマー、リサイクル指標を推奨し、二酸化炭素排出量を削減します。', 'it': 'Raccomanda film a spessore ridotto, biopolimeri certificati e metriche di riciclabilità circolare.', 'tr': 'Karbon ayak izini azaltmak için inceltilmiş filmler, sertifikalı biyopolimerler ve geri dönüşüm metrikleri önerir.', 'ko': '탄소 발자국을 줄이기 위해 두께를 줄인 필름, 인증된 바이오폴리머 및 순환 재활용성 지표를 추천합니다.', 'nl': 'Beveelt dunnere folies, gecertificeerde biopolymeren en circulaire recycleerbaarheidsstatistieken aan.', 'vi': 'Đề xuất màng mỏng hơn, polyme sinh học được chứng nhận và số liệu tái chế để giảm lượng khí thải carbon.', 'id': 'Merekomendasikan film dengan ketebalan yang dikurangi, biopolimer bersertifikat, dan metrik daur ulang.'}, 'feat_packaudit_title': {'en': 'Visual Packaging Audit', 'hi': 'दृश्य पैकेजिंग ऑडिट', 'mr': 'व्हिज्युअल पॅकेजिंग ऑडिट', 'gu': 'વિઝ્યુઅલ પેકેજિંગ ઓડિટ', 'bn': 'ভিজ্যুয়াল প্যাকেজিং অডিট', 'te': 'విజువల్ ప్యాకేజింగ్ ఆడిట్', 'ta': 'காட்சி பேக்கேஜிங் தணிக்கை', 'es': 'Auditoría visual de empaque', 'fr': 'Audit visuel des emballages', 'de': 'Visuelles Verpackungsaudit', 'zh': '可视化包装审核', 'ar': 'تدقيق التعبئة والتغليف المرئي', 'pt': 'Auditoria visual de embalagens', 'ru': 'Визуальный аудит упаковки', 'ja': '視覚的パッケージ監査', 'it': "Audit visivo dell'imballaggio", 'tr': 'Görsel Ambalaj Denetimi', 'ko': '시각적 포장 감사', 'nl': 'Visuele verpakkingsaudit', 'vi': 'Kiểm toán bao bì trực quan', 'id': 'Audit Pengemasan Visual'}, 'feat_packaudit_desc': {'en': 'Upload real container images for visual barrier assessment, seal integrity evaluation, and material matching.', 'hi': 'दृश्य बाधा मूल्यांकन, सील अखंडता और सामग्री मिलान के लिए वास्तविक कंटेनर छवियां अपलोड करें।', 'mr': 'व्हिज्युअल बॅरियर मूल्यांकन, सील अखंडता आणि साहित्य जुळणीसाठी वास्तविक कंटेनर प्रतिमा अपलोड करा.', 'gu': 'વિઝ્યુઅલ અવરોધ મૂલ્યાંકન, સીલ અખંડિતતા અને સામગ્રી મેચિંગ માટે વાસ્તવિક કન્ટેનર છબીઓ અપલોડ કરો.', 'bn': 'ভিজ্যুয়াল বাধা মূল্যায়ন, সীল অখণ্ডতা এবং উপাদান মেলানোর জন্য আসল পাত্রের ছবি আপলোড করুন।', 'te': 'విజువల్ బారియర్ అసెస్\u200cమెంట్, సీల్ సమగ్రత మరియు మెటీరియల్ మ్యాచింగ్ కోసం నిజమైన కంటైనర్ చిత్రాలను అప్\u200cలోడ్ చేయండి.', 'ta': 'காட்சி தடை மதிப்பீடு, முத்திரை ஒருமைப்பாடு மற்றும் பொருள் பொருத்தத்திற்கு உண்மையான கொள்கலன் படங்களை பதிவேற்றவும்.', 'es': 'Suba imágenes reales de contenedores para la evaluación visual de la barrera y la integridad del sellado.', 'fr': "Téléchargez des images réelles de conteneurs pour l'évaluation visuelle des barrières et l'intégrité du scellage.", 'de': 'Laden Sie echte Behälterbilder für visuelle Barrierebewertung und Siegelintegritätsprüfung hoch.', 'zh': '上传真实容器图片以进行视觉阻隔评估、密封完整性检查和材料匹配。', 'ar': 'قم بتحميل صور حقيقية للحاويات لتقييم الحاجز المرئي وسلامة الختم ومطابقة المواد.', 'pt': 'Carregue imagens reais de recipientes para avaliação visual da barreira e integridade da vedação.', 'ru': 'Загружайте реальные фотографии контейнеров для визуальной оценки барьера и целостности швов.', 'ja': '実際の容器画像をアップロードして、視覚的なバリア評価、シールの完全性評価、材料マッチングを行います。', 'it': "Carica immagini reali dei contenitori per la valutazione visiva della barriera e l'integrità della sigillatura.", 'tr': 'Görsel bariyer değerlendirmesi ve sızdırmazlık bütünlüğü için gerçek kap resimlerini yükleyin.', 'ko': '시각적 배리어 평가, 씰 무결성 평가 및 재료 매칭을 위해 실제 용기 이미지를 업로드하세요.', 'nl': 'Upload echte containerbeelden voor visuele barrièrebeoordeling en sealintegriteit.', 'vi': 'Tải lên hình ảnh thùng chứa thực tế để đánh giá rào cản trực quan và tính toàn vẹn của niêm phong.', 'id': 'Unggah gambar wadah nyata untuk penilaian pelindung visual, evaluasi segel, dan pencocokan bahan.'}}

for _key, _lang_map in EXTRA_LOCALIZED_KEYS.items():
    for _lang, _val in _lang_map.items():
        if _lang in TRANSLATIONS and _key not in TRANSLATIONS[_lang]:
            TRANSLATIONS[_lang][_key] = _val
        # Also ensure fallback in English if missing
        if _key not in TRANSLATIONS['en']:
            TRANSLATIONS['en'][_key] = _lang_map.get('en', _val)

# Provide fallback aliases
for _lang in SUPPORTED_LANGUAGES:
    t_dict = TRANSLATIONS.get(_lang, {})
    if 'lbl_origin_city' in t_dict and 'origin_city' not in t_dict:
        t_dict['origin_city'] = t_dict['lbl_origin_city'].replace('*', '').strip()
    if 'lbl_dest_city' in t_dict and 'destination_city' not in t_dict:
        t_dict['destination_city'] = t_dict['lbl_dest_city'].replace('*', '').strip()

# --- EXPANDED 21-LANGUAGE KEYS (EXACT LOCALIZATION) ---
EXPANDED_21_KEYS = {'lbl_origin_city': {'en': 'Origin City *', 'hi': 'प्रस्थान शहर *', 'mr': 'मूळ शहर *', 'gu': 'મૂળ શહેર *', 'bn': 'উৎপত্তি শহর *', 'te': 'ప్రారంభ నగరం *', 'ta': 'புறப்படும் நகரம் *', 'es': 'Ciudad de origen *', 'fr': "Ville d'origine *", 'de': 'Abfahrtsort *', 'zh': '始发城市 *', 'ar': 'مدينة المنشأ *', 'pt': 'Cidade de origem *', 'ru': 'Город отправления *', 'ja': '出発都市 *', 'it': 'Città di origine *', 'tr': 'Kalkış Şehri *', 'ko': '출발 도시 *', 'nl': 'Herkomststad *', 'vi': 'Thành phố xuất phát *', 'id': 'Kota Asal *'}, 'lbl_dest_city': {'en': 'Destination City *', 'hi': 'गंतव्य शहर *', 'mr': 'गंतव्य शहर *', 'gu': 'ગંતવ્ય શહેર *', 'bn': 'গন্তব্য শহর *', 'te': 'చేరుకునే నగరం *', 'ta': 'சேருமிடம் நகரம் *', 'es': 'Ciudad de destino *', 'fr': 'Ville de destination *', 'de': 'Zielort *', 'zh': '目的地城市 *', 'ar': 'مدينة الوجهة *', 'pt': 'Cidade de destino *', 'ru': 'Город назначения *', 'ja': '目的都市 *', 'it': 'Città di destinazione *', 'tr': 'Varış Şehri *', 'ko': '도착 도시 *', 'nl': 'Bestemmingsstad *', 'vi': 'Thành phố đích *', 'id': 'Kota Tujuan *'}, 'origin_city': {'en': 'Origin City', 'hi': 'प्रस्थान शहर', 'mr': 'मूळ शहर', 'gu': 'મૂળ શહેર', 'bn': 'উৎপত্তি শহর', 'te': 'ప్రారంభ నగరం', 'ta': 'புறப்படும் நகரம்', 'es': 'Ciudad de origen', 'fr': "Ville d'origine", 'de': 'Abfahrtsort', 'zh': '始发城市', 'ar': 'مدينة المنشأ', 'pt': 'Cidade de origem', 'ru': 'Город отправления', 'ja': '出発都市', 'it': 'Città di origine', 'tr': 'Kalkış Şehri', 'ko': '출발 도시', 'nl': 'Herkomststad', 'vi': 'Thành phố xuất phát', 'id': 'Kota Asal'}, 'destination_city': {'en': 'Destination City', 'hi': 'गंतव्य शहर', 'mr': 'गंतव्य शहर', 'gu': 'ગંતવ્ય શહેર', 'bn': 'গন্তব্য शहर', 'te': 'చేరుకునే నగరం', 'ta': 'சேருமிடம் நகரம்', 'es': 'Ciudad de destino', 'fr': 'Ville de destination', 'de': 'Zielort', 'zh': '目的地城市', 'ar': 'مدينة الوجهة', 'pt': 'Cidade de destino', 'ru': 'Город назначения', 'ja': '目的都市', 'it': 'Città di destinazione', 'tr': 'Varış Şehri', 'ko': '도착 도시', 'nl': 'Bestemmingsstad', 'vi': 'Thành phố đích', 'id': 'Kota Tujuan'}, 'farmer_advice_stack': {'en': 'Stack crates no more than 4 layers high to prevent crushing the packaging.', 'hi': 'पैकेजिंग को टूटने से बचाने के लिए क्रेटों को 4 परतों से अधिक न रखें।', 'mr': 'पॅकेजिंग दबण्यापासून वाचवण्यासाठी क्रेट्स ४ पेक्षा जास्त थरांमध्ये ठेवू नका.', 'gu': 'પેકેજિંગને દબાવવાથી બચાવવા માટે ક્રેટ્સ 4 સ્તરોથી વધુ ન ગોઠવો.', 'bn': 'প্যাকেজিং ভেঙে যাওয়া রোধ করতে ক্রেটগুলি ৪ স্তরের বেশি স্তূপ করবেন না।', 'te': 'ప్యాకేజింగ్ దెబ్బతినకుండా ఉండటానికి క్రేట్లను 4 లేయర్ల కంటే ఎక్కువ పేర్చవద్దు.', 'ta': 'பேக்கேஜிங் நசுங்குவதைத் தடுக்க கிரேட்களை 4 அடுக்குகளுக்கு மேல் அடுக்க வேண்டாம்.', 'es': 'No apile cajas a más de 4 niveles para evitar aplastar el empaque.', 'fr': "N'empilez pas les cagettes sur plus de 4 couches pour éviter d'écraser l'emballage.", 'de': 'Kisten nicht höher als 4 Lagen stapeln, um ein Quetschen der Verpackung zu verhindern.', 'zh': '板条箱堆叠不得超过4层，以防压坏包装。', 'ar': 'لا تقم بتكديس الصناديق أكثر من 4 طبقات لتجنب سحق العبوة.', 'pt': 'Não empilhe caixas com mais de 4 camadas para evitar esmagar a embalagem.', 'ru': 'Не ставьте ящики более чем в 4 слоя, чтобы не раздавить упаковку.', 'ja': '包装のつぶれを防ぐため、クレートは4段以上積まないでください。', 'it': 'Non impilare le casse per più di 4 strati per evitare di schiacciare la confezione.', 'tr': 'Ambalajın ezilmesini önlemek için kasaları en fazla 4 kat üst üste istifleyin.', 'ko': '포장이 눌리는 것을 방지하기 위해 상자를 4단 이하로만 쌓으세요.', 'nl': 'Stapel kratten niet meer dan 4 lagen hoog om pletten van de verpakking te voorkomen.', 'vi': 'Không xếp thùng cao quá 4 lớp để tránh làm bẹp bao bì.', 'id': 'Jangan menumpuk peti lebih dari 4 lapis untuk mencegah kemasan hancur.'}, 'farmer_advice_circulation': {'en': 'Keep air circulation paths open between rows inside the cargo vehicle.', 'hi': 'कार्गो वाहन के अंदर पंक्तियों के बीच हवा के संचलन के रास्ते खुले रखें।', 'mr': 'वाहतूक वाहनात रांगांमध्ये हवेचा प्रवाह खुला ठेवा.', 'gu': 'વાહનમાં હવાની અવરજવર માટે હરોળો વચ્ચે રસ્તો ખુલ્લો રાખો.', 'bn': 'কার্গো যানের ভেতরে সারির মধ্যে বায়ু চলাচলের পথ খোলা রাখুন।', 'te': 'రవాణా వాహనం లోపల వరుసల మధ్య గాలి ప్రసరణ మార్గాలను తెరిచి ఉంచండి.', 'ta': 'சரக்கு வாகனத்தின் உள்ளே வரிசைகளுக்கு இடையில் காற்று சுழற்சி பாதைகளை திறந்து வைக்கவும்.', 'es': 'Mantenga despejadas las vías de circulación de aire entre filas dentro del vehículo.', 'fr': "Laissez les voies de circulation d'air ouvertes entre les rangées dans le véhicule.", 'de': 'Halten Sie die Luftzirkulationswege zwischen den Reihen im LKW offen.', 'zh': '在货运车辆内的行与行之间保持空气流通通道畅通。', 'ar': 'حافظ على مسارات دوران الهواء مفتوحة بين الصفوف داخل مركبة الشحن.', 'pt': 'Mantenha as vias de circulação de ar abertas entre as fileiras no veículo.', 'ru': 'Оставляйте проходы для циркуляции воздуха между рядами в грузовом отсеке.', 'ja': '貨物車両内の列間に空気循環経路を確保してください。', 'it': "Mantenere aperti i percorsi di circolazione dell'aria tra le file nel veicolo.", 'tr': 'Kargo aracı içindeki sıralar arasında hava sirkülasyonu boşlukları bırakın.', 'ko': '화물 차량 내부의 줄 사이에 공기 순환 통로를 열어 두세요.', 'nl': 'Houd luchtcirculatiewegen tussen rijen in het vrachtvoertuig open.', 'vi': 'Giữ thông thoáng các đường lưu thông không khí giữa các hàng bên trong xe.', 'id': 'Jaga jalur sirkulasi udara tetap terbuka di antara barisan di dalam kendaraan kargo.'}, 'farmer_advice_sun': {'en': 'Never leave packed boxes exposed to direct midday sun on loading bays.', 'hi': 'लोडिंग बे पर पैक किए गए डिब्बों को दोपहर की तेज धूप में कभी न छोड़ें।', 'mr': 'लोडिंग करताना पॅक केलेले खोके दुपारच्या कडक उन्हात उघडे ठेवू नका.', 'gu': 'લોડિંગ પોઇન્ટ પર પેક કરેલા બોક્સને બપોરના સીધા તડકામાં ક્યારેય ન છોડો.', 'bn': 'লোডিং বে-তে প্যাক করা বাক্স সরাসরি দুপুরের রোদে ফেলে রাখবেন না।', 'te': 'లోడింగ్ ప్రదేశాల్లో ప్యాక్ చేసిన బాక్సులను మధ్యాహ్నం ఎండలో నేరుగా ఉంచవద్దు.', 'ta': 'ஏற்றுமதி பகுதிகளில் பேக் செய்யப்பட்ட பெட்டிகளை நண்பகல் வெயிலில் விடாதீர்கள்.', 'es': 'Nunca deje las cajas expuestas al sol directo del mediodía en las bahías de carga.', 'fr': 'Ne laissez jamais les caisses emballées exposées au soleil direct de midi.', 'de': 'Lassen Sie verpackte Kartons auf Laderampen niemals in der prallen Mittagssonne stehen.', 'zh': '切勿在装卸区将包装好的箱子暴露在中午的烈日下。', 'ar': 'لا تترك الصناديق المعبأة معرضة لأشعة الشمس المباشرة عند منصات التحميل.', 'pt': 'Nunca deixe caixas embaladas expostas ao sol direto do meio-dia nas baias de carga.', 'ru': 'Никогда не оставляйте упакованные коробки под прямым полуденным солнцем.', 'ja': '積み込み場所で梱包された箱を真昼の直射日光にさらさないでください。', 'it': 'Non lasciare mai le scatole imballate esposte al sole diretto sulle baie di carico.', 'tr': 'Yükleme alanlarında paketlenmiş kutuları asla doğrudan öğle güneşine maruz bırakmayın.', 'ko': '적재 구역에서 포장된 상자를 한낮의 직사광선에 방치하지 마세요.', 'nl': 'Laat verpakte dozen op laadkades nooit in de felle middagzon staan.', 'vi': 'Không bao giờ để các hộp đã đóng gói tiếp xúc trực tiếp với ánh nắng giữa trưa.', 'id': 'Jangan pernah meninggalkan kotak kemasan terkena sinar matahari siang langsung.'}, 'farmer_advice_dry': {'en': 'Ensure packs stay dry; protect from sudden rain or water spray during transit.', 'hi': 'सुनिश्चित करें कि पैक सूखे रहें; पारगमन के दौरान बारिश या पानी के छींटों से बचाएं।', 'mr': 'पॅक कोरडे राहतील याची खात्री करा; प्रवासात पाऊस किंवा पाण्याच्या फवाऱ्यापासून संरक्षण करा.', 'gu': 'પેક સૂકા રહે તેની ખાતરી કરો; મુસાફરી દરમિયાન વરસાદ કે પાણીથી બચાવો.', 'bn': 'প্যাকগুলি শুকনো রাখুন; ট্রানজিটের সময় হঠাৎ বৃষ্টি বা জল থেকে রক্ষা করুন।', 'te': 'ప్యాక్\u200cలు పొడిగా ఉండేలా చూసుకోండి; రవాణా సమయంలో ఆకస్మిక వర్షం లేదా నీటి నుండి రక్షించండి.', 'ta': 'பேக்குகள் உலர்ந்திருப்பதை உறுதிப்படுத்தவும்; பயணத்தின் போது மழையிலிருந்து பாதுகாக்கவும்.', 'es': 'Asegúrese de que los paquetes permanezcan secos; proteja de la lluvia durante el tránsito.', 'fr': 'Assurez-vous que les paquets restent secs; protégez de la pluie pendant le transport.', 'de': 'Achten Sie darauf, dass Packungen trocken bleiben; vor Regen schützen.', 'zh': '确保包装保持干燥；在运输过程中防止突降暴雨或水花飞溅。', 'ar': 'تأكد من بقاء العبوات جافة؛ احمها من الأمطار أو رذاذ الماء أثناء النقل.', 'pt': 'Garanta que os pacotes permaneçam secos; proteja da chuva durante o transporte.', 'ru': 'Следите за сухостью упаковок; защищайте их от дождя и брызг при транспортировке.', 'ja': 'パックを乾いた状態に保ち、輸送中の突然の雨や水しぶきから保護してください。', 'it': 'Assicurarsi che le confezioni rimangano asciutte; proteggere dalla pioggia durante il trasporto.', 'tr': 'Paketlerin kuru kaldığından emin olun; nakliye sırasında yağmur ve su sıçramasından koruyun.', 'ko': '포장이 건조한 상태를 유지하도록 하세요. 운송 중 비나 물보라로부터 보호하세요.', 'nl': 'Zorg dat verpakkingen droog blijven; bescherm tegen regen tijdens transport.', 'vi': 'Đảm bảo các gói hàng luôn khô ráo; bảo vệ khỏi mưa trong quá trình vận chuyển.', 'id': 'Pastikan kemasan tetap kering; lindungi dari hujan atau percikan air selama perjalanan.'}, 'freshness_preservation': {'en': 'freshness preservation', 'hi': 'ताजगी संरक्षण', 'mr': 'ताजेपणा जतन', 'gu': 'તાજગી જાળવણી', 'bn': 'সতেজতা সংরক্ষণ', 'te': 'తాజాదనం పరిరక్షణ', 'ta': 'புத்துணர்ச்சி பாதுகாப்பு', 'es': 'preservación de frescura', 'fr': 'préservation de la fraîcheur', 'de': 'Frischeerhaltung', 'zh': '保鲜度提升', 'ar': 'الحفاظ على النضارة', 'pt': 'preservação do frescor', 'ru': 'сохранение свежести', 'ja': '鮮度保持', 'it': 'conservazione della freschezza', 'tr': 'tazelik koruması', 'ko': '신선도 보존', 'nl': 'versheidsbehoud', 'vi': 'bảo quản độ tươi', 'id': 'pelestarian kesegaran'}, 'affordable_unit_rate': {'en': 'Affordable down-gauged unit rate', 'hi': 'किफायती डाउन-गेज इकाई दर', 'mr': 'परवडणारा डाऊन-गेज युनिट दर', 'gu': 'કિફાયતી ડાઉન-ગેજ એકમ દર', 'bn': 'সাশ্রয়ী ডাউন-গেজ ইউনিট রেট', 'te': 'సరసమైన డౌన్-గేజ్ యూనిట్ రేటు', 'ta': 'மலிவு குறைக்கப்பட்ட யூனிட் வீதம்', 'es': 'Tarifa unitaria asequible de calibre reducido', 'fr': "Tarif unitaire abordable d'épaisseur réduite", 'de': 'Erschwinglicher Stückpreis durch Dünnschicht', 'zh': '经济实惠的减薄膜单价', 'ar': 'سعر وحدة اقتصادي مع تخفيض السماكة', 'pt': 'Tarifa unitária acessível com espessura reduzida', 'ru': 'Доступный тариф за счет уменьшения толщины', 'ja': '薄肉化による手頃な単価', 'it': 'Tariffa unitaria conveniente con spessore ridotto', 'tr': 'İnceltilmiş ekonomik birim fiyat', 'ko': '두께 감소를 통한 경제적인 단가', 'nl': 'Betaalbaar eenheidstarief door dunnere folie', 'vi': 'Đơn giá phải chăng nhờ giảm độ dày', 'id': 'Tarif unit terjangkau dengan ketebalan optimal'}, 'sustainability_subdesc': {'en': 'Includes down-gauging and circular recyclability.', 'hi': 'डाउन-गेजिंग और चक्रीय पुनर्चक्रण शामिल है।', 'mr': 'डाऊन-गेजिंग आणि चक्रीय पुनर्वापर समाविष्ट आहे.', 'gu': 'ડાઉન-ગેજિંગ અને રિસાયક્લેબિલિટી શામેલ છે.', 'bn': 'ডাউন-গেজিং এবং পুনর্ব্যবহারযোগ্যতা অন্তর্ভুক্ত।', 'te': 'డౌన్-గేజింగ్ మరియు రీసైక్లింగ్ కలిగి ఉంటుంది.', 'ta': 'குறைக்கப்பட்ட தடிமன் மற்றும் மறுசுழற்சி அடங்கும்.', 'es': 'Incluye reducción de calibre y reciclabilidad circular.', 'fr': "Comprend la réduction d'épaisseur et le recyclage circulaire.", 'de': 'Inklusive Materialreduzierung und Recyclingfähigkeit.', 'zh': '包括薄膜减薄与循环可回收性。', 'ar': 'يشمل تقليل السماكة وقابلية إعادة التدوير الدائرية.', 'pt': 'Inclui redução de espessura e reciclabilidade circular.', 'ru': 'Включает уменьшение толщины и возможность переработки.', 'ja': '薄肉化と循環型リサイクル性を含みます。', 'it': 'Include riduzione dello spessore e riciclabilità circolare.', 'tr': 'İnceltme ve döngüsel geri dönüştürülebilirliği içerir.', 'ko': '두께 감소 및 순환 재활용성을 포함합니다.', 'nl': 'Inclusief materiaaldiktevermindering en circulariteit.', 'vi': 'Bao gồm giảm độ dày và khả năng tái chế tuần hoàn.', 'id': 'Termasuk pengurangan ketebalan dan daur ulang sirkular.'}, 'technical_standards': {'en': 'Technical Standards', 'hi': 'तकनीकी मानक', 'mr': 'तांत्रिक मानके', 'gu': 'તકનીકી ધોરણો', 'bn': 'প্রযুক্তিগত মান', 'te': 'సాంకేతిక ప్రమాణాలు', 'ta': 'தொழில்நுட்ப தரநிலைகள்', 'es': 'Normas técnicas', 'fr': 'Normes techniques', 'de': 'Technische Standards', 'zh': '技术标准', 'ar': 'المعايير الفنية', 'pt': 'Padrões técnicos', 'ru': 'Технические стандарты', 'ja': '技術規格', 'it': 'Standard tecnici', 'tr': 'Teknik Standartlar', 'ko': '기술 표준', 'nl': 'Technische normen', 'vi': 'Tiêu chuẩn kỹ thuật', 'id': 'Standar Teknis'}}

for _ekey, _emap in EXPANDED_21_KEYS.items():
    for _elang, _eval in _emap.items():
        if _elang in TRANSLATIONS:
            TRANSLATIONS[_elang][_ekey] = _eval
        if _ekey not in TRANSLATIONS['en']:
            TRANSLATIONS['en'][_ekey] = _emap.get('en', _eval)
